### ISSUE TITLE
Business validation error when trying to create quickbooks item of type Inventory

### ISSUE THREAD

**Issue by pula2000** [intuit/QuickBooks-V3-DotNET-SDK#10]
When we try to create a quickbooks online item, we get a business validation error with below description - 
Business Validation Error: When you create an item, if Track quantity on hand is turned off, the item cannot be of type Inventory.
We do have "track inventory quantity on hand" setting on so this shouldn't be occurring. Would be great if you could look into it?

**Comment by nimisha84** [comment]
Can you open issues related to API on our official support channels? Please use this issue reporting only for SDK.
Go to developer.intuit.com->help. You have an option to submit a support ticket or open a community question. Please add request and response logs for the item and the company id and mention if company is QBO US or global. Is it a Plus company? Please add that detail too. 
I or one of our support team mates will look into it.
