### ISSUE TITLE
Exception in latest 9.2.0 package

### ISSUE THREAD

**Issue by virginijus-servicebridge** [intuit/QuickBooks-V3-DotNET-SDK#100]
Hi,

we tried to update to 9.2.0 version to use Item->ClassRef field and got exception

**Object reference not set to an instance of an object.**

StackTrace:
   at Intuit.Ipp.OAuth2PlatformClient.TokenClientExtensions.RequestRefreshTokenAsync(TokenClient client, String refreshToken, Object extra, CancellationToken cancellationToken) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\TokenClientExtensions.cs:line 55
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.<RefreshTokenAsync>d__56.MoveNext() in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\OAuth2Client.cs:line 465

This is not good,
can you fix it ASAP

P.S. same function works fine with 8.1.0 package

**Comment by nimisha84** [comment]
Checking, i suspect it might be issue if you are calling just refresh. Will update the fix soon. Until then, delisting this package.

**Comment by nimisha84** [comment]
Please try 9.4.0.0 version and let me know if you still see issues

**Comment by virginijus-servicebridge** [comment]
Thank you for quick response and fixes.
I will check it and will provide results as soon as I will get back on that task.

**Comment by Jesse-Hufstetler** [comment]
I'm having the same issue, just got the package from NuGet about two or so hours ago

**Comment by nimisha84** [comment]
@Jesse-Hufstetler you used 9.4.0 or 9.2.0? I would like to see the logs to understand better where it is failing. Can you enable fiddler and run it alongside your code? I don't get the error when testing this on the sample apps we have. So, would need more details.
Fiddler steps-
Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by nimisha84** [comment]
Please check 9.5.0 release. Fixed directory not found exception.

**Comment by Jesse-Hufstetler** [comment]
Looks like it's not an issue related to the network (no network requests fire before the exception). Seems like "AdvancedLogger" is null at this line https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/c26c048f74e5b67bc8046f44abb4c9acd012582d/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/TokenClientExtensions.cs#L31

**Comment by nimisha84** [comment]
Did you try this with 9.5.0? Advance logger should be initialized now with each call. Can you verify once?

**Comment by Jesse-Hufstetler** [comment]
It's still happening on 9.5.0 🙁. The whole thing works if I type 
```csharp
OAuth2Client.AdvancedLogger = new AdvancedLogging(false, false, false, false, "\\");
```
right before I call `RequestRefreshTokenAsync`.

**Comment by nimisha84** [comment]
Can you share a sample code where I can replicate this issue?

**Comment by nimisha84** [comment]
Ok, from what I understand you are actually using TokenClient directly for your calls and that way making OAuth2 calls is deprecated/not officially supported. I have a solution in mind, will discuss more with team and update you then.

**Comment by Jesse-Hufstetler** [comment]
> Are you directly calling TokenClient obj.RequestRefreshTokenAsync and not using the OAuth2Client?

Yes

> I have a solution in mind, will discuss more with team and update you then.

Thanks!

**Comment by nimisha84** [comment]
Yes, I am in California :). The 9.6.0.0 release should fix this issue if you are using old clients. If you move to OAuth2Client for your code, you can take advantage of the new Advanced logger. Docs will be updated shortly for that.
