### ISSUE TITLE
Invalid constructor in V8.1

### ISSUE THREAD

**Issue by NueraInsurance** [intuit/QuickBooks-V3-DotNET-SDK#104]
We have just migrated to .NET core and upgraded to 8.1.0 (latest on Nuget) and I believe there is a bug in the ServiceContext constructors making this unusable (or I'm missing something!):

There are two constructors available:
```
  public ServiceContext(
      string realmId,
      IntuitServicesType serviceType,
      IRequestValidator requestValidator = null,
      IConfigurationProvider configReader = null)
```

and 

```
   public ServiceContext(
      string appToken,
      string realmId,
      IntuitServicesType serviceType,
      IRequestValidator requestValidator = null)
```

Originally we were using the second constructor - however the IppConfiguration is now always NULL in that constructor (looking back at history, the private constructor used to set it to a LocalConfigReader). 

I've built my own IConfigurationProvider and am trying to use the first constructor - however there doesn't seem to be a way to set the AppToken using that and the property does not have a setter on it.

Is this a bug or am I totally missing something?

**Comment by nimisha84** [comment]
Up until 7.5.0, we had support for Apptoken as it supported OAuth1 keys.
When we moved over our SDK in releases>7.5.0 to support only OAuth2, we do not support Apptoken anymore as OAuth2 apps do not expose that param in the app keys anymore. So, you need to use first constructor without Apptoken for OAuth2 (SDK>7.5.0 release). The end date for OAuth1 support is already communicated as Dec 17th, 2019.

**Comment by NueraInsurance** [comment]
@nimisha84 ahh! Understood. So I have to move to OAuth 2 to use any versions >7.5. 

The interesting part here is this is a service-account style integration. It is a batch job that runs to post some JE's from our internal account system. Is there an example of OAuth 2.0 that does NOT require user interaction?

**Comment by nimisha84** [comment]
We support only web apps for OAuth2 (3-legged oauth)
***For desktop apps/server apps/console apps and automated service type apps for Oauth2***

There is no way to bypass the Oauth process. **You will have to do it at least once to make api calls.**
So, if you have a desktop app/service then your customer can use Postman or Oauth2 playground we have, add the app keys and then get the Oauth2 tokens. or you can have a webforms app just for giving them the tokens first time.
Hardcode them in your cutsomer's desktop application/installable. Then keep on refreshing access token using refreshtoken api call until refresh token expires in 100 days.
Then again get new access tokens by playground or postman and repeat api calls until refresh token expires. This would be a cycle of hardcoding tokens every 100 days.
Always save the latest refresh token in your code as once used refresh tokens can expire in 24hrs.

OAuth2 playground-https://developer.intuit.com/v2/ui#/playground

On the developer.intuit.com->Your app tab->Keys->Add this redirect url under your Prod app keys->Redirect url-https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl

Postman-
https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0012_postman

On the developer.intuit.com->Your app tab->Keys->Add this redirect url under your Prod app keys ->Redirect url-https://www.getpostman.com/oauth2/callback

1)You get access token and refresh token manually using Postman or your web code where user authorizes
2)You hard code TOKENs in your code by saving the access token and latest refresh token in DB/permanaent store as access token expires every 1 hr and refresh token every 24hrs.
3)You can make calls without User interaction after refreshing access token using refresh token api once you get the access token from step 1 .
4)Every time refresh token api is called(check any of the web sample apps for oauth2 here-https://github.com/IntuitDeveloper), you have to save the latest value for access token and refresh token in DB.
5)Use the latest refresh token to get new access token and this process continues until 100 days.
6)Then again start with getting a new access token or whenever you have an expired token for various reasons. You will get a 401 error when access token expires or a 400 error when refresh token call fails to refresh access token. Read details in the docs - https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization.

Check this blog from dev where details are mentioned in a blog-
http://www.relasoft.net/KB10004.html

**Comment by NueraInsurance** [comment]
That is actually how we do it now - I setup the initial keys (using the OAuth 1 playground) and then automate the refresh calls. It's unfortunate we have to re-auth every 100 days with user interaction but I can write a utility to do that.

Thanks a ton for the information.

**Comment by nimisha84** [comment]
The refresh token in oauth2 also changes every 24hrs but with a validity of 100 days where you need to re-authorise again. So, it is a rolling 100 days and after one time just use latest refresh token everytime from your last refresh token api call and you will be good indefinitely.
