### ISSUE TITLE
8.1.0 Linq Extender Missing?

### ISSUE THREAD

**Issue by jmawebtech** [intuit/QuickBooks-V3-DotNET-SDK#105]
Hi,

I use this package and MVC 5.3:

  <package id="IppDotNetSdkForQuickBooksApiV3" version="7.5.0" targetFramework="net461" />

I tried to upgrade to 8.1.0 and I get this error:

Intuit.Ipp.LinqExtender cannot be found. Are you missing an assembly reference?

This code shows no where statement:

            return departmentQueryService.Where(a => a.FullyQualifiedName == name).ToList();

Is LinqExtender supported in 8.1.0? If not, what is the alternative?

**Comment by nimisha84** [comment]
We deprecated support for LinqExtender really long back about 2years ago. We removed it completely in the .Net Standard releases , any release >7.5.0. 
Use ExecuteIdsQuery in the QueryService to make your query calls.

**Comment by reinux** [comment]
I'm not particularly opposed to this, but just out of curiosity, what motivated the decision?

**Comment by nimisha84** [comment]
It was a 3rd party lib which was not scalable enough to meet the requirements we had unless major modifications were made to it. There were a couple of bugs too which needed to be resolved in the lib which we could not support further.

**Comment by reinux** [comment]
Interesting. Thanks!
