### ISSUE TITLE
API V3 and .net 4.5?

### ISSUE THREAD

**Issue by calebsandfort** [intuit/QuickBooks-V3-DotNET-SDK#106]
Hi

I am trying to migrate my integration to use OAuth 2.0. My integration currently uses OAuth 1.0, .net 4.5 and version 2.2.0.0 of the Intuit.Ipp dlls.

I tried installing the IppDotDetSdkForQuickBooksApiV3 nuget package, but it failed because it depends on .net 4.6.1.

I'm not currently in a position to upgrade to .net 4.6.1. Is there any way to use OAuth 2.0 and the Intuit.Ipp dlls and stay on .net 4.5?

Any help would be appreciated or guidance would be appreciated

Thanks

**Comment by nimisha84** [comment]
Unfortunately, we cannot support 4.5 because we need to support TLS1.2 which is a default for 4.6.1 and above.
You can choose to continue with the old version of SDK that you have which support 4.5 for the time being and use the direct rest api calls to migrate the oauth1 tokens to oauth2.
Check docs here-

https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/migration

**Comment by calebsandfort** [comment]
Ok, that makes sense. Migrating the tokens doesn't look too bad, but will they work with the old version of the SDK?

Here's how I create my ServiceContext for example:

```
String consumerKey = SysConfig.ServiceProvider.QuickBooksConsumerKey;
                    String consumerSecret = SysConfig.ServiceProvider.QuickBooksConsumerSecret;
                    IntuitServicesType intuitServiceType = IntuitServicesType.QBO;

                    OAuthRequestValidator oauthValidator = new OAuthRequestValidator(SysConfig.ServiceProvider.QuickBooksAccessToken,
                        SysConfig.ServiceProvider.QuickBooksAccessTokenSecret,
                        consumerKey, consumerSecret);
                    _quickBooksContext = new ServiceContext(SysConfig.ServiceProvider.QuickBooksApplicationToken, SysConfig.ServiceProvider.QuickBooksRealm, intuitServiceType, oauthValidator);
                    _quickBooksContext.IppConfiguration.BaseUrl.Qbo = "https://quickbooks.api.intuit.com/";
                    //_quickBooksContext.IppConfiguration.BaseUrl.Qbo = "https://sandbox-quickbooks.api.intuit.com/";
```

Won't that continue to use OAuth 1.0?

**Comment by nimisha84** [comment]
If you do not wish to move to 4.6.1, then you will not be able to use the SDK at all. You will have to change your code to support all HTTP calls directly unfortunately.

**Comment by nimisha84** [comment]
There is a sample here you can refer-
https://github.com/IntuitDeveloper/OAuth2-Dotnet-WithoutSDK

**Comment by calebsandfort** [comment]
Ok, thanks for the info
