### ISSUE TITLE
QueryProcessingError: To email address entered is invalid

### ISSUE THREAD

**Issue by xenno** [intuit/QuickBooks-V3-DotNET-SDK#111]
Please refer to issue as this is related:
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/81

This happens when querying the invoices in minor version 41.

I've masked the realm ID

Request:
RequestUrl: https://quickbooks.api.intuit.com/v3/company/123*****537/query?minorversion=41&requestid=6dc33a0a78a847738939763df65e9ed8, Request Payload:SELECT * FROM Invoice WHERE Balance > '0.0' StartPosition 0 MaxResults 500

Response:
Response Intuit_Tid header: ec2967cc-665f-426f-b9db-b5a573099f0c, Response Payload: {"Fault":{"Error":[{"Message":"Error processing query","Detail":"QueryProcessingError: To email address entered is invalid","code":"4002"}],"type":"ValidationFault"},"time":"2019-11-18T23:45:06.552-08:00"} 

This is client specific. We need the issue identified so that the client can be informed.

It is also related to https://help.developer.intuit.com/s/question/0D50f00006CSiTQCA1/possible-bug-with-minor-version-36-retrieving-invoices-with-multiple-customer-emails

As well as the PHP issue:
https://github.com/intuit/QuickBooks-V3-PHP-SDK/issues/216

**Comment by nimisha84** [comment]
Thanks for doing the research on this issue along with the actual issue. Will check with engineering team and update you

**Comment by xenno** [comment]
I've discovered the data issue. It is related to entering an email address on an invoice. It is possible to save an invoice with an invalid email address. However, the SDK only considers an email address invalid when it is separated by a semicolon, i.e. a@b.com;b@c.com . If it is just a comma or other invalid data like just a word, the invoices will still sync.
The semicolon causes the issue. 

I've tried downgrading the version, however the earliest version I can get on NuGet is version 7.5.0 (minor version 38). This seems to be be an issue after minor version 35.

**Comment by nimisha84** [comment]
Correct. The engineering confirmed this bug for mv >=36. The fix is scheduled for this weekend. So, until that with current Sdk too, you can use mv less than 36 n it will work.

**Comment by xenno** [comment]
Thank you. I've used the latest SDK and set the minor version as follows:
`ServiceContext context = new ServiceContext(realmId, IntuitServicesType.QBO, oauth2Validator);                 
            context.IppConfiguration.MinorVersion = new Intuit.Ipp.Core.Configuration.MinorVersion()
            {
                Qbo = "35"
            };`
It is working

**Comment by nimisha84** [comment]
Great. Please try the same call with mv=41 around next week Wed/Thu
