### ISSUE TITLE
Passing information across in the 'Bill' memo field

### ISSUE THREAD

**Issue by ravtakhar** [intuit/QuickBooks-V3-DotNET-SDK#112]
Trying to pass across a string in the 'Bill' memo field, but it doesn't to be syncing across. 

Showing up as empty on the QuickBooks side of things.

**Comment by MatthewSteeples** [comment]
This may or may not work, but try putting it in the PrivateNote property instead

**Comment by ravtakhar** [comment]
Private note worked!

Thanks
