### ISSUE TITLE
Cannot remove class from item

### ISSUE THREAD

**Issue by virginijus-servicebridge** [intuit/QuickBooks-V3-DotNET-SDK#113]
Using latest 9.6.1 version I can assign and change class for item but I CANNOT remove class.
I tried:

- item.ClassRef = null;
- item.ClassRef = new ReferenceType { Value = ""};
- sparse update
- full update

nothing works, I cannot remove class, looks like API does not listen to my updates for ClassRef.

Is this a limitation, know issue or new bug?

**Comment by rkasaraneni20** [comment]
Looks weird.. Can you please try using the latest minor version and provide us the request and response logs.

**Comment by virginijus-servicebridge** [comment]
Hi,
looks like this is on QBO side, see response from Intuit support:

> Hello Team,
> 
> You are correct. There are few limitations regarding the delete/remove operation on sparse update. We can achieve this using full update.  But anyhow will check with the team if this is coming as an enhancement and if yes by when.
> 
> Sincerely,
> Ramya Kasaraneni
> Intuit Developer Group
>

**Comment by nimisha84** [comment]
The issue was reported for QBO api. Closing as this is not an SDk issue.
