### ISSUE TITLE
ExecuteIdsQuery(pagedQuery) fails when wrapped in Task.Run()

### ISSUE THREAD

**Issue by sheam** [intuit/QuickBooks-V3-DotNET-SDK#114]
The following works:
```var pagedResult = queryService.ExecuteIdsQuery(pagedQuery);```

But if I change it to this:
```
var pagedResult = await Task.Run(() =>
{
       //throws CommunicationException with message" Response stream null or empty
      var result = queryService.ExecuteIdsQuery(pagedQuery);
      return result;
});
```
I get an exception. Is there a way to make this work?

**Comment by rkasaraneni20** [comment]
Hi,
Please refer to one of our samples which has Async methods in it :https://github.com/IntuitDeveloper/SampleApp-CRUD-.Net/blob/master/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/Helper/Helper.cs
We don't support await
