### ISSUE TITLE
QBO Gives 500 error trying to migrate a second time

### ISSUE THREAD

**Issue by DrLeh** [intuit/QuickBooks-V3-DotNET-SDK#115]
Hello, 

We are testing a QBO OAuth1 -> 2 migration for our software. We allow our users to create a QBO linkage, and our QA department only has one QBO account to use for testing our features before we roll it out to all our users. We did the migration once, and it seemed to work, but we ran into other application issues that required re-testing the migration process. We re-authenticated using OAuth1 to re-test the migration process, but every subsequent migration gives a 500 error with no additional information.

Is this expected? Is there no way to re-test the same QBO account Oauth 1 -> 2 migration? Should we get a new account in order to test the migration again, is that our only option?

Here is the code snippet I'm using to do the migration 

```
var oauthValidator = new OAuthRequestValidator(userCredential.AccessToken, userCredential.AccessTokenSecret, QboConfig.ConsumerKey, QboConfig.ConsumerSecret);

var migrationHelper = new OAuth1ToOAuth2TokenMigrationHelper(QboConfig.Environment);

var tokenResponse = migrationHelper.GetOAuth2Tokens(GetScope(), QboConfig.RedirectUrl, QboConfig.ClientId, QboConfig.ClientSecret, oauthValidator);

var webException = tokenResponse.Exception as WebException;
if (webException != null)
{
	Stream receiveStream = webException.Response.GetResponseStream();
	StreamReader readStream = new StreamReader(receiveStream, Encoding.UTF8);
	var errorMessage = readStream.ReadToEnd();
	//errorMessage comes back with no details except "500 Internal server error has occurred"
	_log.Error($"QBO Error migrating tenant {tenantId} to OAuth2: {errorMessage}");
}
if (tokenResponse.IsError)
{
	_log.Error($"QBO Error migrating tenant {tenantId} to OAuth2: {tokenResponse.Error}");
	throw new OAuth2MigrationException(tokenResponse.Error);
}
```

**Comment by rkasaraneni20** [comment]
Can you please provide you app details so that we can check what is the status. As mentioned once you initiate migration the app will be migrated status and we cannot migrate it again. Also, please provide the logs so that we can check the exact issue

**Comment by nimisha84** [comment]
Closing old issue
