### ISSUE TITLE
Nuget error version 9.6

### ISSUE THREAD

**Issue by rgarofalo** [intuit/QuickBooks-V3-DotNET-SDK#117]
Hi,

during the installation of version 9.6 with framework 4.6.1 via nuget I get this error

why?

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not install package 'Microsoft.Extensions.Configuration 2.2.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	

```

**Comment by nimisha84** [comment]
Upgrade your project to 4.7.2 framework or download 2.1.0 version of this dependency on your code. We might need to verify n fix this fir 4.6.1 in our Nuget package. I am on leave until 10th Jan. So, can't verify this suggested fix
