### ISSUE TITLE
Filtering for a lot of basis fields is not supported eg for ITEM fields IncomeAccountRef and ExpenseAccountRef

### ISSUE THREAD

**Issue by dzygar-softgrad** [intuit/QuickBooks-V3-DotNET-SDK#119]
Hello! 

We have best practice of integration our app with Intuit QuickBooks Desktop. It gives mutually benefits and increases the popularization of both apps. Now our customers desire to integrate with QuickBooks Online. 

In two-way sync process can be much data on both sides which are need to merge and make decisions. Our IT team took into account limitations of QBO API (SDK) and adapts our biz-logic for this.

Unfortunately, QBO API (SDK) has very bad bottleneck .
A lot of important QBO fields cannot be filterable via query!
Thus, for search few records by criterias need todo huge load of all QBO entities and only then apply criterias as post-processing.
This is not best practice for keep performance of both systems and their limitations. 
This is also complicated by a lack of support JOIN operations in query.

Simple example: 
we don't want to get ALL ITEMs where TYPE is SERVICE (eg 10 000)
we need to get ITEMs with TYPE is SERVICE and specific IncomeAccountRef, ExpenseAccountRef or w/o some of their (eg 3 only)
smth like: IncomeAccountRef IS NULL OR  IncomeAccountRef = ID

1) What is the reasons of unsupported filters for relation fields between entities in WHERE clause (or JOIN operator)?

2) When is it planned to introduce something similar to SDK (.NET) in the future?

We hope that our requirements are not extraordinary.
Thank you for understanding!

**Comment by rkasaraneni20** [comment]
Unfortunately SDK does not support this. This is an API limitation and SDK is just a wrapper

**Comment by dzygar-softgrad** [comment]
Thank you for your answer.

Is where a chance that this will be implemented in the nearest or middle future?

We understand that SDK is just wrapper for the API.
But we hope, that the SDK being developed under the leadsheep and/or in close collaboration with API's dev team.
Such feature will make a benefit to everyone (incl. API limitations and performance).

Thank you.

**Comment by rkasaraneni20** [comment]
Thanks that would be a great implementation. Will let the team know and see how soon we can implement it. As of now, it is not in their bucket list.
