### ISSUE TITLE
Serialization of SalesReceipt containing SalesItemLineDetail is wrong

### ISSUE THREAD

**Issue by genifycom** [intuit/QuickBooks-V3-DotNET-SDK#124]
In DotNet Standard 2.0 (using this with Xamarin)

SalesReceipts contain Lines. A Line object needs to record a SalesItemLineDetail. As far as I can tell, the code looks like this:

      sales_receipt.Line = new Line[] {
                new Line { LineNum = "1", Description = "One Oak Table with 2 chairs", Amount = 560.0m,
                    DetailType = LineDetailTypeEnum.SalesItemLineDetail, AnyIntuitObject = new SalesItemLineDetail{ Qty = 1, ItemRef = new ReferenceType{ name = "Cash Till Sales", Value = "7" } }
                },
            };

But when this is Serialized using JsonConvert.SerializeObject(sales_receipt), the resulting JSON contains the text:

      "AnyIntuitObject": {
        "ItemRef": {
          "name": "Cash Till Sales",
          "Value": "7"
        }
      }

which is rejected by the API. It should contain:

      "SalesItemLineDetail": {
        "ItemRef": {
          "name": "Cash Till Sales",
          "value": "7"
        }
      },

How are we supposed to code the correct serialization in c#?

**Comment by genifycom** [comment]
BTW, this is in DotNet Standard 2.0 (using this with Xamarin)

**Comment by nimisha84** [comment]
https://gist.github.com/IntuitDeveloperRelations/6500373 - Please check this code sample. For salesreceipt, a similar code should work for salesitemlinedetail.

**Comment by nimisha84** [comment]
invoiceLine.AnyIntuitObject = lineSalesItemLineDetail; <- you might be missing this kind of an assignment for your object
