### ISSUE TITLE
Intuit.Ipp.Core.Rest.SyncRestHandler.ParseResponse -> System.String.Concat -> System.OutOfMemoryException

### ISSUE THREAD

**Issue by bpleasantj** [intuit/QuickBooks-V3-DotNET-SDK#126]
I am encountering a System.OutOfMemoryException in a production environment:
```
[OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.]
System.String.Concat(String str0, String str1, String str2, String str3) +87
Intuit.Ipp.Core.Rest.SyncRestHandler.ParseResponse(HttpWebResponse httpWebResponse) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-S
Intuit.Ipp.Core.Rest.SyncRestHandler.CallRestService(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPD
Intuit.Ipp.Core.Rest.SyncRestHandler.GetResponse(HttpWebRequest request) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNe
Intuit.Ipp.QueryFilter.QueryService`1.ExecuteIdsQuery(String idsQuery, QueryOperationType queryOperationType) in C:\Users\nshrivastava\Documents\
```
Unfortunately, I am unable to reproduce in my development environment to further investigate.
The executed query would have been something like the following:
`SELECT * FROM Payment ORDERBY Id STARTPOSITION 1001 MAXRESULTS 1000`

I am using quite an old version (8.0.0) of this package though. If someone could verify that issue this is fixed in the latest version (10.0.0.3) I would definitely upgrade. However, I am wary of doing so otherwise, since there are obviously risks involved.

**Comment by nimisha84** [comment]
Since this issue is specific to your server and not a generic issue, I would suggest you to have one of sample apps deployed on your server, update the Nuget package to latest version on the sample app and enable SDK logs too. Then enable one of the query calls and test the sample app. Do you get the same error? If yes, then you can see the details in the logs to see what is the issue and fix it.

**Comment by bpleasantj** [comment]
This was due to my Azure platform being set to 32-bit.
Once I set it to 64-bit, the problem went away.

**Comment by nimisha84** [comment]
Great. Good to know that you were able to resolve this.

Thanks,
Nimisha
