### ISSUE TITLE
Error when creating invoice with TimeActivity Link

### ISSUE THREAD

**Issue by SankarAtkku** [intuit/QuickBooks-V3-DotNET-SDK#127]
Refer the following XML payload (invoice with TimeActivity Link)
```
<Invoice xmlns=\"http://schema.intuit.com/finance/v3\">
  `<DocNumber>250005</DocNumber>
  <TxnDate>2020-04-11T00:00:00-04:00</TxnDate>
  <LinkedTxn>
    <TxnId>147</TxnId>
    <TxnType>TimeActivity</TxnType>
  </LinkedTxn>
  <LinkedTxn>
    <TxnId>148</TxnId>
    <TxnType>TimeActivity</TxnType>
  </LinkedTxn>
  <LinkedTxn>
    <TxnId>149</TxnId>
    <TxnType>TimeActivity</TxnType>
  </LinkedTxn>
  <LinkedTxn>
    <TxnId>150</TxnId>
    <TxnType>TimeActivity</TxnType>
  </LinkedTxn>

  <Line>
    <Description>Onsite consulting services provided by John Johnson
Client/Project: Test G PROJECT</Description>
    <Amount>3000</Amount>
    <DetailType>SalesItemLineDetail</DetailType>
    <SalesItemLineDetail>
      <ItemRef name=\"Regular Rate\">43</ItemRef>
      <UnitPrice>125</UnitPrice>
      <Qty>24</Qty>
      <TaxCodeRef name=\"NON\">NON</TaxCodeRef>
    </SalesItemLineDetail>
  </Line>
  <CustomerRef name=\"John Johnson\">99</CustomerRef>
  <CustomerMemo>John Johnson_01/01/2020 - 01/04/2020</CustomerMemo>
  <BillAddr>
    <Id>177</Id>
    <Line1>200 MIDDLESEX ESSEX TPKE</Line1>
    <Line2>STE 203A</Line2>
    <City>Iselin</City>
    <CountrySubDivisionCode>NJ</CountrySubDivisionCode>
    <PostalCode>08830</PostalCode>
  </BillAddr>
  <ShipAddr>
    <Id>178</Id>
    <Line1>200 MIDDLESEX ESSEX TPKE</Line1>
    <Line2>STE 203A</Line2>
    <City>Iselin</City>
    <CountrySubDivisionCode>NJ</CountrySubDivisionCode>
    <PostalCode>08830</PostalCode>
  </ShipAddr>
  <SalesTermRef name=\"Net 15\">2</SalesTermRef>
  <DueDate>2020-04-26T00:00:00-04:00</DueDate>
  <PONumber>PO-25003</PONumber>
  <PrintStatus>PrintComplete</PrintStatus>
  <EmailStatus>EmailSent</EmailStatus>
</Invoice>
````

**Throwing error, when try to save Invoice.**
Intuit.Ipp.Exception.IdsException: BadRequest. Details: Business Validation Error: When linking a TimeActivity (id:150) to an Invoice you must also link it to a sales line item , Business Validation Error: When linking a TimeActivity (id:149) to an Invoice you must also link it to a sales line item , Business Validation Error: When linking a TimeActivity (id:148) to an Invoice you must also link it to a sales line item , Business Validation Error: When linking a TimeActivity (id:147) to an Invoice you must also link it to a sales line item ,  ---> Intuit.Ipp.Exception.ValidationException: Validation Exception was thrown.Details:Business Validation Error: When linking a TimeActivity (id:150) to an Invoice you must also link it to a sales line item.Business Validation Error: When linking a TimeActivity (id:149) to an Invoice you must also link it to a sales line item.Business Validation Error: When linking a TimeActivity (id:148) to an Invoice you must also link it to a sales line item.Business Validation Error: When linking a TimeActivity (id:147) to an Invoice you must also link it to a sales line item.
   --- End of inner exception stack trace ---
   at Intuit.Ipp.DataService.DataService.Add[T](T entity) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.DataService\DataService.cs:line 241

-- Please note, same XML payload was working perfectly till April 01,2022. 

SDK version 8.1 used, upgraded to 11.0 - Same error.
Minor version tried: 40, 47
.Net framework :4.7
Web Application: ASP.Net, MVC, C#

-- Same error when tried via API Explorer

Any help is appreciated.

Sankar

**Comment by nimisha84** [comment]
Hi, 

Going forward, for any API issues, I would ask you to post your issue on the Help page on developer.intuit.com. Our team will look into it.

I created an invoice and linked a timeactivity to it from UI and read it via API explorer. Here is what I got-
{
 "QueryResponse": {
  "Invoice": [
   {
    "AllowIPNPayment": false,
    "AllowOnlinePayment": false,
    "AllowOnlineCreditCardPayment": false,
    "AllowOnlineACHPayment": false,
    "domain": "QBO",
    "sparse": false,
    "Id": "1441",
    "SyncToken": "0",
    "MetaData": {
     "CreateTime": "2020-04-14T10:46:26-07:00",
     "LastUpdatedTime": "2020-04-14T10:46:26-07:00"
    },
    "CustomField": [
     {
      "DefinitionId": "1",
      "Name": "Crew #",
      "Type": "StringType"
     }
    ],
    "DocNumber": "1214",
    "TxnDate": "2020-04-14",
    "CurrencyRef": {
     "value": "USD",
     "name": "United States Dollar"
    },
    "ExchangeRate": 1,
    "LinkedTxn": [
     {
      "TxnId": "21",
      "TxnType": "TimeActivity"
     }
    ],
    "Line": [
     {
      "Id": "1",
      "LineNum": 1,
      "Amount": 20,
      "LinkedTxn": [
       {
        "TxnId": "21",
        "TxnType": "TimeActivity",
        "TxnLineId": "1"
       }
      ],
      "DetailType": "SalesItemLineDetail",
      "SalesItemLineDetail": {
       "ItemRef": {
        "value": "2",
        "name": "Hours"
       },
       "UnitPrice": 5,
       "Qty": 4,
       "ItemAccountRef": {
        "value": "1",
        "name": "Services"
       },
       "TaxCodeRef": {
        "value": "TAX"
       },
       "TaxClassificationRef": {
        "value": "EUC-99990202-V1-00020000"
       }
      }
     },
     {
      "Amount": 20,
      "DetailType": "SubTotalLineDetail",
      "SubTotalLineDetail": {}
     }
    ],
    "TxnTaxDetail": {
     "TxnTaxCodeRef": {
      "value": "7"
     },
     "TotalTax": 1.8,
     "TaxLine": [
      {
       "Amount": 1.25,
       "DetailType": "TaxLineDetail",
       "TaxLineDetail": {
        "TaxRateRef": {
         "value": "4"
        },
        "PercentBased": true,
        "TaxPercent": 6.25,
        "NetAmountTaxable": 20
       }
      },
      {
       "Amount": 0.2,
       "DetailType": "TaxLineDetail",
       "TaxLineDetail": {
        "TaxRateRef": {
         "value": "5"
        },
        "PercentBased": true,
        "TaxPercent": 1,
        "NetAmountTaxable": 20
       }
      },
      {
       "Amount": 0.35,
       "DetailType": "TaxLineDetail",
       "TaxLineDetail": {
        "TaxRateRef": {
         "value": "12"
        },
        "PercentBased": true,
        "TaxPercent": 1.75,
        "NetAmountTaxable": 20
       }
      }
     ]
    },
    "CustomerRef": {
     "value": "26",
     "name": "Travis Waldron"
    },
    "BillAddr": {
     "Id": "27",
     "Line1": "78 First St.",
     "City": "Monlo Park",
     "CountrySubDivisionCode": "CA",
     "PostalCode": "94304",
     "Lat": "37.4585825",
     "Long": "-122.1352789"
    },
    "ShipAddr": {
     "Id": "27",
     "Line1": "78 First St.",
     "City": "Monlo Park",
     "CountrySubDivisionCode": "CA",
     "PostalCode": "94304",
     "Lat": "37.4585825",
     "Long": "-122.1352789"
    },
    "FreeFormAddress": true,
    "ShipFromAddr": {
     "Id": "682",
     "Line1": "123 Sierra Way, San Pablo, CA, 87999, USA"
    },
    "DueDate": "2020-04-14",
    "TotalAmt": 21.8,
    "HomeTotalAmt": 21.8,
    "ApplyTaxAfterDiscount": false,
    "PrintStatus": "NeedToPrint",
    "EmailStatus": "NotSet",
    "BillEmail": {
     "Address": "Travis@Waldron.com"
    },
    "Balance": 21.8,
    "HomeBalance": 21.8,
    "TaxExemptionRef": {}
   }
  ],
  "startPosition": 1,
  "maxResults": 1,
  "totalCount": 1
 },
 "time": "2020-04-14T10:47:20.064-07:00"
}

You can see that Linked txn is required on the salesitemlinedetail too. Try matching your request and then follow the error details in any to resolve this.



Thanks,
Nimisha
