### ISSUE TITLE
Question (not issue) - is this measured in milliseconds or seconds?

### ISSUE THREAD

**Issue by AugustZellmer** [intuit/QuickBooks-V3-DotNET-SDK#128]
The class Intuit.Ipp.OAuth2PlatformClient.TokenResponse contains a function called AccessTokenExpiresIn (also RefreshTokenExpiresIn) which returns a long representing a period of time. Is this long the number of milliseconds until it expires? or is this the number of seconds until it expires?

Thanks!

**Comment by nimisha84** [comment]
It is seconds. Check the detailed info in docs here-https://developer.intuit.com/app/developer/qbpayments/docs/develop/authentication-and-authorization/oauth-2.0#step-5-exchange-authorization-code-for-refresh-and-access-tokens

**Comment by AugustZellmer** [comment]
Cool thanks!
