### ISSUE TITLE
C# DotNet Core 3.1 Samples

### ISSUE THREAD

**Issue by genifycom** [intuit/QuickBooks-V3-DotNET-SDK#129]
Where can we find DotNet Core samples for creating each of the transaction types?

I can find the JSON based samples but not c# samples.

Thanks

**Comment by nimisha84** [comment]
https://github.com/IntuitDeveloper/OAuth2_DotnetCore_MVC5_SampleApp

**Comment by nimisha84** [comment]
All other examples for all SDKs are also available under the same github account.
