### ISSUE TITLE
Exception throw even if logging disabled

### ISSUE THREAD

**Issue by ribbles** [intuit/QuickBooks-V3-DotNET-SDK#13]
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/08ff7722f8dd8cc558b841f48ac32aade778b28c/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.Core/Configuration/LocalConfigReader.cs#L107

**Comment by nimisha84** [comment]
How did you enable logging? Please provide code or config settings?
To manage exception handling in your code: 

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging 

If you still do not see error details, enable logging in code using these three lines: 

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator); 
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true; 
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

Is your directory path reachable?
