### ISSUE TITLE
SalesItemLineDetail does not expose UnitPrice property

### ISSUE THREAD

**Issue by chadwixk** [intuit/QuickBooks-V3-DotNET-SDK#132]
Looking at the [API Entity Reference for SalesReceipt](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/salesreceipt#create-a-salesreceipt) it shows you can set the unit price.

However, the [SDK SalesItemLineDetail class properties](https://developer-static.intuit.com/SDKDocs/QBV3Doc/IPPDotNetDevKitV3/html/02c74c63-add7-5ac2-df33-ed8f0cfd7750.htm) does not include it.

**Comment by nimisha84** [comment]
Please check the unit price code here-
https://gist.github.com/IntuitDeveloperRelations/6500373
