### ISSUE TITLE
Is this a bug? Journal Entries uploaded out of order.

### ISSUE THREAD

**Issue by AugustZellmer** [intuit/QuickBooks-V3-DotNET-SDK#133]
I use (essentially) the following piece of code code upload a list of Journal Entries to QB Online. 

````
var dataService = new Intuit.Ipp.DataService.DataService(GetServiceContext());
List<List<Intuit.Ipp.Data.Line>> entries = GetEntries();
foreach (var entry in entries)
{
	var journalEntry = new Intuit.Ipp.Data.JournalEntry
	{
		Line = entry.ToArray()
	};
	dataService.Add<Intuit.Ipp.Data.JournalEntry>(journalEntry);
}
````
When this code is executed, all of the journal entries in `entries` are correctly uploaded to my QB Online company. However, the Journal Number of the uploaded journals are [sometimes out of order.](https://drive.google.com/file/d/10fRKolDB9_ZXjN8oVw9B5fEzQSylNSWj/view?usp=sharing) Granted, the order of the journal entries is not very important, and I've confirmed that all of the data in each journal entry is correct, but it's just kind of strange that the order would be wrong like that.

I'm not sure if this is the right place to ask this question, but I didn't know where else to do so - 
Do you know what's causing these numbers to be out of order? Am I somehow using the SDK wrong? Or am I seeing the results of some sort of race condition on the QB servers? Or what's up?

Any ideas appreciated. Thanks!

**Comment by rkasaraneni20** [comment]
Thanks for bringing to our notice. Created a ticket with the reports team and will let you know once it is resolved.

**Comment by nimisha84** [comment]
Was you issue resolved via ticket?

**Comment by AugustZellmer** [comment]
I don't have visibility to the ticket; has it been completed?

**Comment by nimisha84** [comment]
Please share the bug num and I can verify

**Comment by AugustZellmer** [comment]
I don't have the bug number, nor the ticket.

@rkasaraneni20  created the ticket for me; they'd have that information.

**Comment by rkasaraneni20** [comment]
@nimisha84 @AugustZellmer  The ticket number is BDPLT-1712.

@AugustZellmer  Thanks for the patience. The team is looking this ticket. Please use the above ticket number for further references

**Comment by AugustZellmer** [comment]
@rkasaraneni20 no problem. thanks for the help with this!

**Comment by nimisha84** [comment]
I have closed this issue here. You can always ask for a status update through support.

**Comment by AugustZellmer** [comment]
Okay sure. Thanks!
