### ISSUE TITLE
Missing fields Profit and Loss Report Detail

### ISSUE THREAD

**Issue by ecunarro** [intuit/QuickBooks-V3-DotNET-SDK#137]
Hi,

I'm using your sdk to consume profit and loss detail report. 

I'm calling the P&LDetail report with a custom period and "compare against period" custom (first image of qb online) from the API. However, there are two fields "missing" (low_pp_date and high_pp_date) on the sdk api (see second image). Do you plan to add them in the future? 

![first image](https://user-images.githubusercontent.com/58698786/87965718-97db7780-ca92-11ea-8e39-c392304866b4.png)

![image](https://user-images.githubusercontent.com/58698786/87966128-323bbb00-ca93-11ea-9db3-bdbeb1aea6e8.png)

Thanks for your time and sdk, it is really helpful,

Regards,

**Comment by nimisha84** [comment]
Although it is not not offically supported as per docs, I have added it in the SDK. It may or may not work given we officially do not support it.

**Comment by nimisha84** [comment]
Use the latest SDK version

**Comment by ecunarro** [comment]
Hi @nimisha84 

Thanks for you quick response. I update to the latest version and apparently QB Online API ignore the fields. Hopefully in the near future they will add them as it is really very useful and is already supported on Qb Online Profit and Loss report.

Thanks!

Regards

**Comment by ecunarro** [comment]
Hi @nimisha84 

I did some more test and I see that the fields are not sent. I can set theirs value in the report service (see first image), however they are not included on the request (second image). Can this be possible?

![image](https://user-images.githubusercontent.com/58698786/88331415-4b4aa300-cd03-11ea-8497-507d3a55c901.png)


**
![image](https://user-images.githubusercontent.com/58698786/88331297-1cccc800-cd03-11ea-8c3d-dc3b9ce76d1e.png)
**

Thanks!

**Comment by nimisha84** [comment]
Let me test it out more and see what is going on. Will keep you posted.

**Comment by nimisha84** [comment]
Looks like the API is not supporting it as stated earlier and therefore schema used by the SDK also does not exposes these fields. Therefore even though you can set them up using the code changes I made, they will not work. I will probably remove them next release until API team starts supporting them.

**Comment by ecunarro** [comment]
Thanks for your response. 

I just did some testing and found out that another field was missing. Maybe is this the reason that it is ignoring the previous two fields? (see image)

![image](https://user-images.githubusercontent.com/58698786/88403631-2d347f80-cda3-11ea-81a0-956f77e5d567.png)

As you can see when I select "compare against period" and select custom, there is a third attribute for this checkbox. Maybe this was the reason for theirs API ignore the two previous field added.

Thanks for your time.

Regards

**Comment by nimisha84** [comment]
Thanks for pointing that out. I added it and fixed another code issue which was causing these fields to not get added to the request. This is from the latest 14.2.0.0 version of the SDK but the API does not supports this field even when we request for it.


GET https://sandbox-quickbooks.api.intuit.com/v3/company/123146090856284/reports/ProfitAndLoss?low_pp_date=2020-01-01&high_pp_date=2020-06-01&custom_pp=yes&minorversion=38&requestid=451f42abef0140dd99ca920c5bd2ee86 HTTP/1.1

HTTP/1.1 200 OK

{"Header":{"Time":"2020-07-24T11:56:16-07:00","ReportName":"ProfitAndLoss","DateMacro":"this calendar year-to-date","ReportBasis":"Accrual","StartPeriod":"2020-01-01","EndPeriod":"2020-07-24","SummarizeColumnsBy":"Total","Currency":"USD","Option":[{"Name":"AccountingStandard","Value":"GAAP"},{"Name":"NoReportData","Value":"false"}]},"Columns":{"Column":[{"ColTitle":"","ColType":"Account","MetaData":[{"Name":"ColKey","Value":"account"}]},{"ColTitle":"Total","ColType":"Money","MetaData":[{"Name":"ColKey","Value":"total"}]}]},"Rows":{"Row":[{"Header":{"ColData":[{"value":"Income"},{"value":""}]},"Rows":{"Row":[{"ColData":[{"value":"Fees Billed","id":"5"},{"value":"100.00"}],"type":"Data"},{"Header":{"ColData":[{"value":"Landscaping Services","id":"45"},{"value":"100.00"}]},"Rows":{"Row":[{"Header":{"ColData":[{"value":"Job Materials","id":"46"},{"value":""}]},"Rows":{"Row":[{"ColData":[{"value":"Fountains and Garden Lighting","id":"48"},{"value":"186.00"}],"type":"Data"}]},"Summary":{"ColData":[{"value":"Total Job Materials"},{"value":"186.00"}]},"type":"Section"},{"Header":{"ColData":[{"value":"Labor","id":"51"},{"value":""}]},"Rows":{"Row":[{"ColData":[{"value":"Installation","id":"52"},{"value":"350.00"}],"type":"Data"},{"ColData":[{"value":"Maintenance and Repair","id":"53"},{"value":"2408.00"}],"type":"Data"}]},"Summary":{"ColData":[{"value":"Total Labor"},{"value":"2758.00"}]},"type":"Section"}]},"Summary":{"ColData":[{"value":"Total Landscaping Services"},{"value":"3044.00"}]},"type":"Section"},{"ColData":[{"value":"Name_05310","id":"86"},{"value":"300.00"}],"type":"Data"},{"ColData":[{"value":"Name_f9c60","id":"82"},{"value":"100.00"}],"type":"Data"},{"ColData":[{"value":"Services","id":"1"},{"value":"1633.00"}],"type":"Data"},{"ColData":[{"value":"Shipping Income","id":"840"},{"value":"12.00"}],"type":"Data"}]},"Summary":{"ColData":[{"value":"Total Income"},{"value":"5189.00"}]},"type":"Section","group":"Income"},{"Summary":{"ColData":[{"value":"Gross Profit"},{"value":"5189.00"}]},"type":"Section","group":"GrossProfit"},{"Header":{"ColData":[{"value":"Expenses"},{"value":""}]},"Rows":{"Row":[{"ColData":[{"value":"Dues & Subscriptions","id":"10"},{"value":"3.00"}],"type":"Data"},{"ColData":[{"value":"Equipment Rental","id":"29"},{"value":"89.00"}],"type":"Data"},{"Header":{"ColData":[{"value":"Job Expenses","id":"58"},{"value":""}]},"Rows":{"Row":[{"Header":{"ColData":[{"value":"Cost of Labor","id":"59"},{"value":"0.00"}]},"Rows":{"Row":[{"ColData":[{"value":"Maintenance and Repairs","id":"61"},{"value":"-33.00"}],"type":"Data"}]},"Summary":{"ColData":[{"value":"Total Cost of Labor"},{"value":"-33.00"}]},"type":"Section"}]},"Summary":{"ColData":[{"value":"Total Job Expenses"},{"value":"-33.00"}]},"type":"Section"},{"Header":{"ColData":[{"value":"Utilities","id":"24"},{"value":""}]},"Rows":{"Row":[{"ColData":[{"value":"Telephone","id":"77"},{"value":"156.50"}],"type":"Data"}]},"Summary":{"ColData":[{"value":"Total Utilities"},{"value":"156.50"}]},"type":"Section"}]},"Summary":{"ColData":[{"value":"Total Expenses"},{"value":"215.50"}]},"type":"Section","group":"Expenses"},{"Summary":{"ColData":[{"value":"Net Operating Income"},{"value":"4973.50"}]},"type":"Section","group":"NetOperatingIncome"},{"Summary":{"ColData":[{"value":"Net Income"},{"value":"4973.50"}]},"type":"Section","group":"NetIncome"}]}}


You can see only default headers are returned in response.

**Comment by ecunarro** [comment]
I'm glad it helped you. Thanks for you help! Do you know when this fields will be added?

Regards

**Comment by nimisha84** [comment]
Hi,

I have created an internal enhancement for this but team will prioritize and work on it based on other developer's needs too. So, it might not be supported very soon.

Here is the internal num for your reference-
BDPLT-1772

Thanks,
Nimisha

**Comment by ecunarro** [comment]
Thanks for your help and time Namisha!

I will be following this issue. Let me know when you have any update.

Regards,

**Comment by nimisha84** [comment]
Closing this as you can follow up on the request number I shared over the support in future. I don't see that it was prioritized as yet.
