### ISSUE TITLE
Master branch does not build

### ISSUE THREAD

**Issue by RJBreneman** [intuit/QuickBooks-V3-DotNET-SDK#14]
I am having trouble compiling IppDotNetDevKitCSV3.sln.  I’m not sure but I’m guessing it is because of circular references.  For example, Intuit.Ipp.Core references Intuit.Ipp.Retry which in turn references Intuit.Ipp.Core.  Do you have any suggestions?  Thanks.

**Comment by nimisha84** [comment]
Replied on your support ticket

**Comment by RJBreneman** [comment]
For others information...
There is a trick to compiling their source code.
Their projects have many circular references.  
They side-stepped that issue by having post-build steps in the projects that copy the output to a 'SDK Assemblies' folder that is a peer of the solution 'Code' folder.
Then their circular references actually point to those assemblies instead of the peer projects in the solution.

However, their git source does not contain the 'SDK Assemblies' folder.
This means their solution will not compile unless you create that folder and populate it with pre-compiled assemblies.
So, create that folder and drop their pre-compiled libraries in there.
Their git source comes with something like a 'IppDotNetSdkForQuickBooksApiV3.4.0.0.0.nupkg' file.
Give that file a .zip extension and you can grab a copy of the libraries from there.

**Comment by brightertools** [comment]
I have tried this and the solution still doesn't build without errors.

Is there anything else to do to get this to compile without errors? I need to reference the code in a project to test some API connectivity, I have a situation where I cannot use the SDK but need to call the API directly and want to see exactly what the SDK is sending to the API.

**Comment by nimisha84** [comment]
@brightertools - You can try out this approach too. In your code, remove all local SDK related lib from each class lib project and instead use nuget to add all those references using IPP .Net SDK package. Then do a clean build and the SDK Assemblies folder will then have correct local assemblies. 
Then remove Nuget Package/uninstall from all class lib projects and then reference the local assemblies from SDK assemblies folder in each class lib project. This will help you build the project again using local assembly references.
