### ISSUE TITLE
Profit&Loss option '%Expenses' Column

### ISSUE THREAD

**Issue by ecunarro** [intuit/QuickBooks-V3-DotNET-SDK#140]
Hi

We are having an issue when requesting the Profit & Loss Report Detail including the column "Comparte to: % of Expenses" for .net API. The Report works just fine for "% of incomes" and other options, however is start throwing an exception when selecting "% of Expenses". See images for more information:

![image](https://user-images.githubusercontent.com/58698786/90794698-76fd8080-e2e3-11ea-95a2-c1400618c257.png)

Thanks for your time

Regards,

**Comment by nimisha84** [comment]
Can you share the raw logs using Serilog or Fiddler here? Steps are available on readme. Sorry, totally missed the notification on this issue.

**Comment by nimisha84** [comment]
Also, do you see the param name reported here in the docs under query a param?
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/report-entities/profitandlossdetail

**Comment by nimisha84** [comment]
Sorry, I see this is linked to https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/137 which I already responded. Closing this as not supported by API yet
