### ISSUE TITLE
Fix missing comments in the code for classes/functions/props

### ISSUE THREAD

**Issue by nimisha84** [intuit/QuickBooks-V3-DotNET-SDK#153]
Fix missing comments in the code for classes/functions/props

**Comment by hey-mikey** [comment]
I'd like to work on this.

**Comment by nimisha84** [comment]
Thanks, please go ahead and submit a PR

**Comment by hey-mikey** [comment]
Just so I'm in the right area, is there a particular solution I should be sticking to, or is this for everything in the code base?

**Comment by nimisha84** [comment]
For every project in this -https://github.com/intuit/QuickBooks-V3-DotNET-SDK/tree/master/IPPDotNetDevKitCSV3/Code. Ignore the 
OAuth2-Dotnet_UsingSDK  sample.

**Comment by ssshweta** [comment]
This looks like a big repo. Can I contribute as well? and @hey-mikey and I can divide the work?

**Comment by hey-mikey** [comment]
I just got swamped at my day job, unfortunately. If @ssshweta is interested, I'd say go right ahead. Not sure how soon I'll be able to come back to this.

**Comment by nsinghal12** [comment]
@nimisha84 Can I also work on this if a part of this is still available.

**Comment by nimisha84** [comment]
Please go ahead and submit a PR @nsinghal12

**Comment by ssshweta** [comment]
@nimisha84 @nsinghal12 FYI, I have already started working on it. But I do not mind if someone else also wants to contribute.

**Comment by nimisha84** [comment]
@nsinghal12 @ssshweta please syn up amongst yourself for the projects you are fixing the comments on, so that your PRs do not overlap. Thanks

**Comment by ssshweta** [comment]
@nsinghal12 I am working on all the services. You can pick up Test projects.

**Comment by nsinghal12** [comment]
@ssshweta Hey, I am caught up at work. Please feel free to go ahead and take up complete issue. Thanks!
