### ISSUE TITLE
UnitPrice API line item field is not supported in SDK

### ISSUE THREAD

**Issue by MaximillianC** [intuit/QuickBooks-V3-DotNET-SDK#158]
Line items in certain entities (like ItemBasedExpenseLineDetail) support a UnitPrice field in the API, but the .NET SDK does not support reading/writing that field.

**Comment by nimisha84** [comment]
See this sample code. Line 56, 57
https://gist.github.com/IntuitDeveloperRelations/6500373#file-v3-qbo-invoice-create-saleslineitem-cs-L56-L57
