### ISSUE TITLE
QueryValidationError: property 'AcctNum' is not queryable

### ISSUE THREAD

**Issue by rbiq** [intuit/QuickBooks-V3-DotNET-SDK#163]
Why am I not able to retrieve a customer using Customer.AcctNum property as filter in the query? I am unable to save your Id on our side. Is there any other reliable I can lookup the customer without using your id property?

```
QueryService<Customer> customerQuery = new QueryService<Customer>(context);
            List<Customer> customers = customerQuery.ExecuteIdsQuery($"SELECT * FROM Customer where AcctNum = '{customerNo}'").ToList();
            return customers.FirstOrDefault();
```

> {"QueryValidationError: property 'AcctNum' is not queryable , "}

**Comment by rbiq** [comment]
I was trying to use it in the filter only after confirming the property showed up on Customer. Can you please confirm if there's any other way I could use it this way? Also when I try to run the same query for Vendor and Account it results in the same error. So clearly something is amiss.
![](https://files.slack.com/files-pri/TNN3RH1CY-F01G1V1V90W/image.png)

**Comment by rkasaraneni20** [comment]
@rbiq Will look into the customer schema and update the documentation accordingly for customer. But for vendor and Account -AcctNum is a valid property but it is not filterable. The property which are mentioned as filterable are only queryable.

**Comment by rbiq** [comment]
@rkasaraneni20 can you please suggest a placeholder on Customer where I can store my customer no so it's easier for me to query? I'm unable to store your Customer.Id however need to look up a customer. I thought AcctNum would be that field. Please let me know at the earliest. thanks!

**Comment by rkasaraneni20** [comment]
@rbiq Please reach out to the support [team.](https://help.developer.intuit.com/s/) They can help you with the above feature.
