### ISSUE TITLE
Could not load file or assembly 'Serilog.Sinks.RollingFile, Version=2.0.0.0

### ISSUE THREAD

**Issue by sadjadbp** [intuit/QuickBooks-V3-DotNET-SDK#164]
We've upgraded from IppDotNetSdkForQuickBooksApiV3 14.4.2 to 14.4.4 and immediately started getting below error

```
Exception Type: System.IO.FileNotFoundException
Exception Message: Could not load file or assembly 'Serilog.Sinks.RollingFile, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'. The system cannot find the file specified.
Stack Trace: at Intuit.Ipp.Core.Rest.AdvancedLogging..ctor(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForRollingFile, String serviceRequestLoggingLocationForFile)
at Intuit.Ipp.Core.CoreHelper.GetAdvancedLogging(ServiceContext serviceContext)
at Intuit.Ipp.Core.Rest.RestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId)
at Intuit.Ipp.Core.Rest.SyncRestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId)
at Intuit.Ipp.DataService.DataService.FindAll[T](T entity, Int32 startPosition, Int32 maxResults
```

Reverting back fixed the issue, tried to clean the solution (delete bin and obj folder) same issues with latest version.

all we are doing is simple fetch like 

```csharp
var dataService = await CreateDataServiceAsync().ConfigureAwait(false);
return dataService.FindAll(new Item()).ToList();
```

**Comment by rkasaraneni20** [comment]
Thanks fo bringing to our notice. The core reference is still using obsolete references. Will look into it and release a new package

**Comment by chadwixk** [comment]
Also these two SeriLog packages are deprecated. Is there any plan for replacing these?

![image](https://user-images.githubusercontent.com/5115308/101994991-da8d2e80-3c83-11eb-9407-b37c0060c685.png)

**Comment by ryanbeaz** [comment]
I'm running into this as well...any plans for a fix soon?

**Comment by Honsl** [comment]
I am having the same issue.

**Comment by southernskip** [comment]
Me as well

**Comment by CollinViz** [comment]
If anyone is working in Dotnet core netcoreapp3.1 This build worked for me. I had to dotnet remove all the packages and add the below.

<PackageReference Include="IppDotNetSdkForQuickBooksApiV3" Version="14.4.4" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Xml" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="12.0.3" />
    <PackageReference Include="RestSharp" Version="106.11.7" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="2.1.3" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="3.1.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="1.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.Literate" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.RollingFile" Version="3.3.0" />
    <PackageReference Include="Serilog.Sinks.Trace" Version="2.1.0" />
    <PackageReference Include="SerilogTraceListener" Version="3.2.0" />
    <PackageReference Include="StackExchange.Redis" Version="2.2.4" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="5.0.0" />

**Comment by Honsl** [comment]
@CollinViz What Packages did you remove? And what did you add?
> If anyone is working in Dotnet core netcoreapp3.1 This build worked for me. I had to dotnet remove all the packages and add the below.

**Comment by knadt** [comment]
What I had to do to get it working.

1. ```powershellInstall-Package Serilog.Sinks.RollingFile```
2.  ```powershellInstall-Package Serilog.Sinks.Literate```
```csharp
  Log.Logger = new LoggerConfiguration()
                .WriteTo.RollingFile("log-{Date}.txt")
                .CreateLogger();

            Log.Logger = new LoggerConfiguration()
                .WriteTo.LiterateConsole()
                .CreateLogger();
```
It works for me in the mean time...

![image](https://user-images.githubusercontent.com/16526578/105773461-370e8980-5f64-11eb-91d9-3311fb709a4b.png)

**Comment by CollinViz** [comment]
@knadt @Honsl - I have edited my comment - did not realize that it did not show the packages - I am running on Linux using dotnet core.
```
dotnet add package IppDotNetSdkForQuickBooksApiV3 --version 14.4.4 
dotnet add package Newtonsoft.Json --version 12.0.3  
dotnet add package RestSharp --version 106.11.7  
dotnet add package Serilog --version 2.10.0  
dotnet add package Serilog.Enrichers.Environment --version 2.1.3  
dotnet add package Serilog.Enrichers.Thread --version 3.1.0  
dotnet add package Serilog.Extensions.Logging --version 3.0.1
dotnet add package Serilog.Settings.Configuration --version 3.1.0  
dotnet add package Serilog.Sinks.Console --version 3.1.1  
dotnet add package Serilog.Sinks.Debug --version 1.0.1  
dotnet add package Serilog.Sinks.File --version 4.1.0  
dotnet add package Serilog.Sinks.Literate --version 3.0.0 
dotnet add package Serilog.Sinks.RollingFile --version 3.3.0
dotnet add package Serilog.Sinks.Trace --version 2.1.0
dotnet add package SerilogTraceListener --version 3.2.0
dotnet add package StackExchange.Redis --version 2.2.4
dotnet add package System.Configuration.ConfigurationManager --version 5.0.0
```

**Comment by rkasaraneni20** [comment]
@sadjadbp @CollinViz @knadt @chadwixk @ryanbeaz @Honsl @southernskip 
Thanks for bringing to our notice and apologies for the late reply
We fixed the issue and released a new version in our SDK. Please use latest version IppDotNetSdkForQuickBooksApiV3" Version="14.6.0" and let us know if there is any issue
