### ISSUE TITLE
How to manage inventory info for items in QBO?

### ISSUE THREAD

**Issue by rbiq** [intuit/QuickBooks-V3-DotNET-SDK#166]
Can you please provide an example on how to update inventory information for items created in QBO? It's not clear in your documentation. Going by this post I found online there's no inventory endpoint we simply have to call a method to update qtys on an item. But then how is inventory history created in QBO? How can we tell QBO that set 10 units aside because they have been flagged for QC or are simply damaged and hence not ready for sale? https://help.developer.intuit.com/s/question/0D50f000058N8GZCA0/how-to-adjust-inventory-in-qbo-using-api

I'd really appreciate any kind of help on this asap.

**Comment by rkasaraneni20** [comment]
@rbiq Looks like this is requirement specific question not related to SDK issue. Can you please reach out to the support [team](https://help.developer.intuit.com/s/).
