### ISSUE TITLE
Missing property on Invoice 

### ISSUE THREAD

**Issue by rbiq** [intuit/QuickBooks-V3-DotNET-SDK#167]
Trying to apply an invoice to the corresponding credit memo as shown below per your documentation:
![image](https://user-images.githubusercontent.com/18170071/101714569-d1c01100-3a67-11eb-9f1e-11b813f81efd.png)

However I'm getting a red squiqqly saying the property doesn't exists on the object. Is it ok to use NameAndId or will it cause problems? Please suggest what to use for InvoiceRef.Name field.
![image](https://user-images.githubusercontent.com/18170071/101714242-2616c100-3a67-11eb-81c6-ae8c55d0237b.png)

**Comment by rkasaraneni20** [comment]
Can you please check which locale and minor version you are working
