### ISSUE TITLE
Missing creditcard fee regions

### ISSUE THREAD

**Issue by chris-appinno** [intuit/QuickBooks-V3-DotNET-SDK#174]
We received an error on serializing a Payment Response from the API using the Payment Client.
***Error converting value "domestic" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 993.) ---> Newtonsoft.Json.JsonSerializationException: Error converting value "domestic" to type 'System.Nullable`1[Mollie.Api.Models.Payment.Response.CreditCardFeeRegion]'. Path 'details.feeRegion', line 1, position 993. ---> System.ArgumentException: Requested value 'domestic' was not found.***
Looking in the Assembly Browser the value was indeed not there in the latest release (V14.6.0.0).
Looking at the API Documentation at mollie (https://docs.mollie.com/reference/v2/payments-api/get-payment) I found 3 missing fee regions namely: amex-intra-eea, intra-eu-corporate and domestic.
Would it be possible to add these?

**Comment by rkasaraneni20** [comment]
@chris-appinno Can you please let us know what is the exact entity you are trying to use and did you try doing the same request using our developer portal(https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/account).

**Comment by nimisha84** [comment]
Hey @chris-appinno We don't have support for a Payments dotnet SDK. Also, it looks like you are referencing some other APIs which we do not own. We own the APIs listed here- https://developer.intuit.com

**Comment by chris-appinno** [comment]
@nimisha84 @rkasaraneni20 my apologies, It seems I posted this in the wrong package. Please ignore it and sorry to have wasted your time.

**Comment by nimisha84** [comment]
no worries. :)
