### ISSUE TITLE
Serilog error

### ISSUE THREAD

**Issue by mlenow** [intuit/QuickBooks-V3-DotNET-SDK#176]
I have tried two new projects and continue to receive this error when I update the installed NuGet packages:

Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.

[TypeLoadException: Could not load type 'Serilog.ConsoleLoggerConfigurationExtensions' from assembly 'Serilog.Sinks.Debug, Version=2.0.0.0, Culture=neutral, PublicKeyToken=24c2f752a8e58a10'.]
   Intuit.Ipp.OAuth2PlatformClient.OAuthAdvancedLogging..ctor(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForFile, String serviceRequestLoggingLocationForFile) in C:\Users\rkasaraneni\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Helpers\OAuthAdvancedLogging.cs:212
   Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.GetAuthorizationURL(List`1 scopes) in C:\Users\rkasaraneni\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.OAuth2PlatformClient\Client\OAuth2Client.cs:322

I cannot figure out how to fix this.

**Comment by Megaventory** [comment]
I have the same problem. Also, this got unlisted? https://www.nuget.org/packages/IntuitOAuth2PlaformClient/

![image](https://user-images.githubusercontent.com/5417157/108626003-9faf3000-7456-11eb-9ce8-6cc5557c4dfc.png)

**Comment by Megaventory** [comment]
I am not sure you'll get a reply soon from the Intuit team. You need to downgrade your Serilog.Sinks.Debug to 1.0.1 for this to work. I could not find another solution.

**Comment by mlenow** [comment]
Thank you!

I really appreciate this help.

Regards,


[cid:905ae7a6-3ceb-4fe0-a161-a33697127ddd]<https://www.bridgecap.ca/>



Dylan Gallagher
Bridge Capital

http://www.linkedin.com/in/gallagherdylan


________________________________

**Comment by MikeBloise77** [comment]
THANK YOU [Megaventory](https://github.com/Megaventory)!  Downgrading to 1.0.1 worked for me.
