### ISSUE TITLE
Support for .Net Full Framework 4.6.1 and 4.7.2?

### ISSUE THREAD

**Issue by charcoalgray99** [intuit/QuickBooks-V3-DotNET-SDK#177]
Your readme states full support for 4.6.1 and 4.7.2.

However, you have a dependency on Serilog.Extensions.Logging >=3.0.1 which only supports .net standard 2.0

Do you even use this package?

**Comment by MatthewSteeples** [comment]
netstandard 2.0 assemblies run [mostly fine](https://docs.microsoft.com/en-us/dotnet/standard/net-standard) on .NET 4.6.1
