### ISSUE TITLE
Calling ExecuteIdsQuery asynchronously?

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#180]
How can we call ExecuteIdsQuery asynchronously?

**Comment by nimisha84** [comment]
We don't have async support for queries. The SDKs are in maintenance mode now and we are only fixing bugs if needed. Therefore, there was no work done to move the old async to async await for asynchronous calls. The OAuth2PlatformClient is more recently added and therefore you will see it supports async await.

**Comment by clement911** [comment]
Is this documented anywhere? This new OAuth2PlatformClient?
I just read all the docs and samples and could find no reference to it.
We are just starting to build a quickbooks integration and would like to use the best sdk for the long term. Can you advise?

**Comment by nimisha84** [comment]
OAuth2PlatformClient is available within this SDK for OAuth2 calls only for getting tokens to make Quickbooks Online API calls using that token.
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/tree/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient

Examples for oAuth2 calls and details are documented here-
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/openid-connect

Other details are here-
https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net

Readme for this SDK too has some details

**Comment by clement911** [comment]
Thank you for that, however, we are quite concerned to learn that the SDKs are only in 'maintenance mode'.
Can you explain what that means for the future of the .NET SDK? Is another .NET SDK in the works?
Are you saying that it will never be possible to call Data queries asynchronously? It certainly would go against the best practices of the last several years.

**Comment by nimisha84** [comment]
The SDKs(Java, PHP, .Net) were designed for QBO v3 API. Going forward we do have a plan to expose the next version of the API and that will be graphql based. Still some time in when that will be released for general availability. Therefore any new work for refactoring existing SDK code is halted. But, we do keep solving for bugs or any new feature releases(new schema) on these SDKs. For Graphql apis, there will not be a need for any SDKs except probably the existing one which we already support for OAuth2 as a part of this SDK too.
Are you saying that it will never be possible to call Data queries asynchronously?
In current state of affairs- yes

**Comment by clement911** [comment]
Got it. Good to hear that a GraphQL based API is in the works.

**Comment by clement911** [comment]
For anyone else that might be interested, [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) supports async querying

**Comment by clement911** [comment]
Hi @nimisha84 
Would you be able to comment on the status of this new upcoming APIs?
We are making a pretty steep investment and commitment to the QuickBooks platform and we are concerned of betting on the current v3 API if it will be deprecated in the future , or if it won't have access to newest features.

We read this post: https://blogs.intuit.com/blog/2020/04/30/api-roadmap-past-present-and-future/
It seems to indicate that the v4/graphql API was cancelled.
Can you please clarify?
Will v3 have access to new features? Will it be deprecated?

**Comment by nimisha84** [comment]
The new set of Graphql based orchestration APIs are in progress and open to some beta payroll partners. QBO graphql APIs are still work in progress. The V3 APIs are going to stay for a while until the new API is vetted out for QBO/Accounting domain too. We will continue to update the V3 API for any new features until then.

https://blogs.intuit.com/blog/2020/04/30/api-roadmap-past-present-and-future/ - This was an old graphql API we are talking about. This was cancelled and our new Graphql orchestration APIs were redesigned after this. They will be released at some point in future but I don't have a date for you.

**Comment by nimisha84** [comment]
V3 and the new API will continue to coexist for sometime

**Comment by clement911** [comment]
ok.
How can I get access to the beta program?
