### ISSUE TITLE
Calling ExecuteIdsQuery with JSON instead of XML

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#181]
It seems that `ExecuteIdsQuery`  returns XML instead of JSON.
How can we use JSON instead?

**Comment by nimisha84** [comment]
You can define the format of request and reponse in the ServiceContext object or using config:
https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net/configuration#serialization-and-compression-formats

**Comment by clement911** [comment]
That worked, thank you.
