### ISSUE TITLE
Clarification about datetime and timezones

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#182]
According to https://developer.intuit.com/app/developer/qbo/docs/develop/rest-api-features#time-stamps-and-time-zones, the datetime fields contain an offset.

So, it would be best if the SDK used `DateTimeOffset` instead of `DateTime`, otherwise the offset is lost.

Can you confirm what the SDK does with the offset? Is the `DateTime` converted to the local server timezone? To UTC?
Please consider changing all the `DateTime` properties to `DateTimeOffset`, so that the SDK works correctly and the behavior is clear. (Note that `DateTimeOffset` converts implicetely to `DateTime`)

**Comment by nimisha84** [comment]
The time is saved in company's timezone but QBO API always returns Pacific time. The devs should then convert the datetime they get in PT to their local timezone. Since, the SDK wrapper was created as DateTime initially(about 10-11years back almost) and many devs use the SDK, changing the format of the response to DateTimeOffset will break all existing integrations. Therefore, it will continue to be a DateTime

**Comment by clement911** [comment]
> The devs should then convert the datetime they get in PT to their local timezone

Can you provide a code sample on how to convert the date time field to UTC.
For example, say I query a list of customers with `SELECT * FROM Customer`. How would I convert the `CreateTime` and `LastUpdatedTime` to UTC.

> Since, the SDK wrapper was created as DateTime initially(about 10-11years back almost) and many devs use the SDK, changing the format of the response to DateTimeOffset will break all existing integrations. Therefore, it will continue to be a DateTime

Then why don't you increment the major version to make such changes? It's a standard industry wide practice. If you don't, you'll never be able to evolve the SDK and will carry forward all of the design issues forever.

**Comment by nimisha84** [comment]
You can check the docs here-
https://docs.microsoft.com/en-us/dotnet/api/system.timezoneinfo.converttimetoutc?view=net-5.0

To your second question, again we are not doing any major updates to the SDKs as there are some new minorversion updates still happening on the api and we want to support them by just minor version updates on SDK as well. There have been not been more than 2-3 devs who have had concerns with the date format and therefore this was never prioritized given we are in maintenance mode and only doing bug fixes or minor version updates

**Comment by clement911** [comment]
I am familiar with these docs, but it depends on what your SDK does when it deserializes the datetime, since the offset won't be preserved.
Does it convert to the local server time zone? To UTC? Is the DateTime.Kind property set accordingly?

**Comment by clement911** [comment]
For anyone else that might be interested, [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) uses DateTimeOffset for all datetime properties.

**Comment by clement911** [comment]
Thanks @ascott18 for the info.

However we are now using [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) instead of the official SDK, which supports modern .NET such as async, DateTimeOffset, nullable properties, etc...
