### ISSUE TITLE
Converting  RefreshTokenExpiresIn and AccessTokenExpiresIn to UTC datetime

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#183]
Strangely, the RefreshTokenExpiresIn and AccessTokenExpiresIn  are `long`.
I understand why the API returns a long but the SDK should abstract that away and return UTC DateTime IMO.
How do we convert to UTC DateTime?

**Comment by clement911** [comment]
Or maybe they should be `TimeSpan`  if they represent a duration and not a date.

**Comment by clement911** [comment]
Is this the right way to get the datetime when the token will expire?

`DateTime.UtcNow.AddSeconds(token.AccessTokenExpiresIn)`

**Comment by nimisha84** [comment]
https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization/oauth-2.0#step-5-exchange-authorization-code-for-refresh-and-access-tokens
x_refresh_token_expires_in | The remaining lifetime, in seconds, for the connection, after which time the user must re-grant access.

expires_in | The remaining lifetime of the access token in seconds. The value  always returned is 3600 seconds (one hour). Use the refresh token to get  a fresh one.

There was decision made to intentionally return back the what internal api send back. The value is in seconds. That ways devs can choose the time own they want to map it too for their backend.

**Comment by nimisha84** [comment]
Your code looks correct

**Comment by clement911** [comment]
TimeSpan can easily be converted to seconds with TimeSpan.TotalSeconds so IMO it would have been a better design to use TimeSpan but I can live with the current behavior.
