### ISSUE TITLE
Static or instance?

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#185]
It's not clear to us if the SDK objects are meant to be instantiated on each use or stored in a static variable.

Can you please clarify?
We have that same question for `OAuth2Client`, `QueryService`, `DataService`, `ServiceContext`, etc...

**Comment by nimisha84** [comment]
Should be static for a user session.
Check out-
https://github.com/IntuitDeveloper
https://github.com/IntuitDeveloper/OAuth2-Dotnet_UsingSDK
https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2
https://github.com/IntuitDeveloper/HelloWorldApp-MVC5-Dotnet

You can check other examples as well in the samples git repo

**Comment by clement911** [comment]
What do you mean exactly by 'user session'?
Can you also explain what is the reason it should be static?

**Comment by nimisha84** [comment]
When any of your Qbo admin user/customer connects to your app (which uses the sdk) first time, your app gets access and refresh token for that admin and you save it to DB along with expiry. This token once generated is passed to ServiceContext object using the access token and that is needed only once for that admin user session. Same is the case for all services(Dataservice, QueryService etc.) which use the servicecontext object. The samples might have both examples. Using the same servicecontext you can make api calls using all services as long as you keep using the same access token and refreshing it as per 100 day policy
