### ISSUE TITLE
Log files created automatically

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#186]
We noticed that some logs files get automatically created in C:\Users\<user>\AppData\Local\Temp even though we didn't enable logging.
Is it supposed to be enabled by default?
How do we turn it off?

**Comment by nimisha84** [comment]
Can you check the details in the Readme to be sure if some config is not enabled? I will create a bug if you do notice the issue in the followup.

**Comment by clement911** [comment]
What readme?

**Comment by nimisha84** [comment]
The readme of this Sdk. It has instructions for loggers

**Comment by clement911** [comment]
Oh I see.
We have not enabled logging, but files are generated anyway.

![image](https://user-images.githubusercontent.com/3426504/114140650-db239200-9910-11eb-8ea2-0e70a78dd59a.png)

**Comment by nimisha84** [comment]
Created a bug, should be fixed in next release , 2-3 weeks from now

**Comment by clement911** [comment]
Great, looking forward to it.

**Comment by nimisha84** [comment]
Fixed in 14.6.1
