### ISSUE TITLE
Querying page of entities return entities with a DELETED status

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#187]
We query a page of entities via the QueryService.
When we inspected the list of entities returned, the entities contain a status property, which is set to DELETED!

**Comment by nimisha84** [comment]
Do not use Status field. It is not supported unless mentioned in API ref docs for any entity.
The SDK is a wrapper on the QBO schema and supports all fields schema exposes but QBO API will only return fields which are mentioned as supported in the docs.
https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/account

**Comment by clement911** [comment]
For anyone else that might be interested, [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) uses a nullable status property, such that it is null unless returned by the API.
