### ISSUE TITLE
SELECT COUNT(*) creates N entities for no reasons

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#188]
I hope you don't take it the wrong way but I'm pretty shocked by the state of the .NET SDK.

Querying the COUNT will create as many objects as the total count!
So, if there are 1 Million invoices, it will create 1 Million objects for absolutely no reason.

Can you not just return the COUNT value somehow?!

![image](https://user-images.githubusercontent.com/3426504/114015076-9b559f80-9869-11eb-8156-a24d1f3c7149.png)

Is there another more efficient way to get the count?

**Comment by clement911** [comment]
Is it possible to add a new method to return just the count?
I'm happy to do a PR.

**Comment by nimisha84** [comment]
Yes, that’s right. We can expose a new method but there were some issues around either xml or Json deserialisation because of the way Sdk deserializes the objects. Please go ahead with your PR. Otherwise, we will take a look at this in may 1 week’s  Sdk fixes release

**Comment by clement911** [comment]
For anyone else that might be interested, [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp) simply returns the totalcount property return by the API

**Comment by nimisha84** [comment]
14.6.1. supports this now.

**Comment by clement911** [comment]
thanks
