### ISSUE TITLE
CDC returns entity with a wrong deleted status

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#189]
Calling CDC I get some entities back with a status of DELETED even though the entities were just updated!

Also, how do we get the maxResults and startPostion property, in case we need to know we have to paginate because the results contain more than 1,000 entities?

Also, how do we get the time property?

![image](https://user-images.githubusercontent.com/3426504/114200463-85bda400-9955-11eb-9fef-ab9df25743c2.png)

**Comment by nimisha84** [comment]
Default maxreuslts for any query is 100
            QueryService<Invoice> in1 = new QueryService<Invoice>(context);
            var inn2 = in1.ExecuteIdsQuery("Select * From Invoice").ToList();
You can do a .Count to get the maxresults for your original query as the SDK does not exposes this in response.

Queries like below have startposition and maxresults passed in the query and your code is already aware of the values.
            Invoice inn1 = in1.ExecuteIdsQuery("Select * From Invoice where Id='27' StartPosition 1 MaxResults 1").First();

For the time, you can use the current time for query run as a workaround. 

For the CDC issue, please log the request and response and report this to support via developer.intuit.com->?(help)

**Comment by clement911** [comment]
In light of the issues and limitations we've reported, we've decided to create a new open source .NET SDK for QBO.

**Comment by Megaventory** [comment]
@clement911 cool! Can you share here the repo url?

**Comment by clement911** [comment]
@Megaventory sure I will let you know when we publish it on GitHub

**Comment by nimisha84** [comment]
Thanks for the upcoming contribution to community @clement911

**Comment by clement911** [comment]
@Megaventory we published our first nuget version of our QBO .Net SDK.

https://github.com/better-reports/QuickBooksSharp

**Comment by Megaventory** [comment]
@clement911 great!

**Comment by nimisha84** [comment]
That is an awesome turnaround @clement911 . Thanks for your contribution.

**Comment by clement911** [comment]
Thanks 😀
Feel free to list it in the docs as an unofficial .net sdk

**Comment by nimisha84** [comment]
Fixed in 14.6.1 release
