### ISSUE TITLE
`Batch.CDCResponse.exceptions` always empty?

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#19]
I can see (https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.DataService/Batch.cs#L605) only `CDCResponse.entities` filled. How to work with exceptions in case of CDC query?

**Comment by nimisha84** [comment]
You should always get an IdsException with aggregated exception details.
