### ISSUE TITLE
Mention community sdk in docs?

### ISSUE THREAD

**Issue by clement911** [intuit/QuickBooks-V3-DotNET-SDK#192]
Hi there,

Would it be possible to mention [QuickBooksSharp](https://github.com/better-reports/QuickBooksSharp), which is a modern .NET SDK for QuickBooks API in the docs at https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net

I noticed that the other languages do mention their own community SDK so I'd appreciate if you could mention ours as well so that more people can contribute.

**Comment by nimisha84** [comment]
I have updated the docs. Should be available in the next release of docs. I was anyways going to update the docs about your contribution this sprint but thanks for the reminder  and your contribution

**Comment by clement911** [comment]
Great. Can you let me know once the updated docs are live?

**Comment by nimisha84** [comment]
This is released-https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net/community-sdks

Congrats and thanks for contributing!
