### ISSUE TITLE
QBOApiLogs-098098098098.txt files in C:\Windows\Temp?

### ISSUE THREAD

**Issue by chadwixk** [intuit/QuickBooks-V3-DotNET-SDK#193]
I was cleaning up our production server today and noticed these files. They contain sensitive information and there are a ton of them as there is one or every request. 

They seem to look like request/response logs. But our web.config has request/response logging disabled, and even if it were enabled, that is not the path we specify to write them. 

`<requestLog enableRequestResponseLogging="false" requestResponseLoggingDirectory="C:\inetpub\wwwroot\website\Logs\Intuit" />`

Here's a partial screenshot of one of the file's contents (clipped to not show sensitive info)
![image](https://user-images.githubusercontent.com/5115308/118079454-77f4a780-b375-11eb-938b-95bc5884f127.png)

Any ideas on what is causing these files to be written?

**Comment by nimisha84** [comment]
Yeah, this was a bug which we recently fixed in https://github.com/intuit/QuickBooks-V3-DotNET-SDK/releases/tag/V14.6.1.0. Please update to this version and this should be fixed.
