### ISSUE TITLE
Consider renaming Intuit.Ipp.Data.Task

### ISSUE THREAD

**Issue by pablo-martinez** [intuit/QuickBooks-V3-DotNET-SDK#194]
There could be ambiguous reference type issues when using Intuit.Ipp.Data; and using System.Threading.Tasks; in the same file.
This occurs when you want to implement an async method with a void return, so you need to use Task as a return type, and this is conflicting with your "IppTask" Task type.

**Comment by nimisha84** [comment]
Again agree with you. But as suggested in other issues, please either do a PR or fork and update your copy or use the other community SDK shared by @clement911

**Comment by clement911** [comment]
In https://github.com/better-reports/QuickBooksSharp we avoid the problem by naming the Task class `QbTask`
