### ISSUE TITLE
Consider enclosing the configuration in appsettings.json

### ISSUE THREAD

**Issue by pablo-martinez** [intuit/QuickBooks-V3-DotNET-SDK#195]
Currently, you have to add a bunch of keys to the root configuration file.
In large projects this could be conflicting with names that are very generic, as per your [Configuration](https://developer.intuit.com/app/developer/qbo/docs/develop/sdks-and-samples-collections/net/configuration#configuration-file-structure) docs.

These are very generic names (Logger, Security, Service, etc), and are not only very likely to conflict with other configuration names, but you also lose context of what those configs are intended for, unless you add comments.
Consider enclosing them like:
"QuickBooksV3": {
    .............. all your generic config names ..............
}

**Comment by nimisha84** [comment]
Your suggestions are valuable to us.
You are right but we are not doing any major enhancements to the SDK or any changes that can impact other devs using the SDK as we are are having these SDKs in maintenance mode. Only new API release related updates will be added to the SDKs going forward or any bug that need a fix will be released.
I would suggest to fork the SDK and change it as per your need or submit PRs for changes that are not breaking the existing devs. Or you can use the above referred SDK.

If you can submit a PR for this, I will be happy to merge.

Thanks.
