### ISSUE TITLE
Intuit.Ipp.DataService.Batch.ExecuteAsync() not really async

### ISSUE THREAD

**Issue by pablo-martinez** [intuit/QuickBooks-V3-DotNET-SDK#196]
This method has the signature of an async method but it's really not awaitable.
public void ExecuteAsync(); should return a Task like:
public Task ExecuteAsync();

**Comment by clement911** [comment]
Hi @pablo-martinez .
You might want to consider using https://github.com/better-reports/QuickBooksSharp , which is a community-supported QBO SDK I recently built, with true support for async.

**Comment by pablo-martinez** [comment]
@clement911 thanks for your answer. Did you implement batch operations?

**Comment by nimisha84** [comment]
HI Pablo, 

Your suggestions are valuable to us.
You are right but we are not doing any major enhancements to the SDK or any changes that can impact other devs using the SDK as we are are having these SDKs in maintenance mode. Only new API release related updates will be added to the SDKs going forward or any bug that need a fix will be released.
I would suggest to fork the SDK and change it as per your need or submit PRs for changes that are not breaking the existing devs. Or you can use the above referred SDK.

Thanks.

**Comment by clement911** [comment]
@pablo-martinez , https://github.com/better-reports/QuickBooksSharp#batch now supports batch operations in version 1.4
