### ISSUE TITLE
Issue with dependecy locks

### ISSUE THREAD

**Issue by knopa** [intuit/QuickBooks-V3-DotNET-SDK#198]
System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.FileLoggerConfigurationExtensions.File(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, System.String, System.IFormatProvider, System.Nullable`1<Int64>, Serilog.Core.LoggingLevelSwitch, Boolean, Boolean, System.Nullable`1<System.TimeSpan>, Serilog.RollingInterval, Boolean, System.Nullable`1<Int32>, System.Text.Encoding, Serilog.Sinks.File.FileLifecycleHooks)'.
   at Intuit.Ipp.Core.Rest.AdvancedLogging..ctor(Boolean enableSerilogRequestResponseLoggingForDebug, Boolean enableSerilogRequestResponseLoggingForTrace, Boolean enableSerilogRequestResponseLoggingForConsole, Boolean enableSerilogRequestResponseLoggingForFile, String serviceRequestLoggingLocationForFile)
   at Intuit.Ipp.Core.CoreHelper.GetAdvancedLogging(ServiceContext serviceContext) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\CoreHelper.cs:line 193
   at Intuit.Ipp.Core.Rest.RestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\RestHandler.cs:line 134
   at Intuit.Ipp.Core.Rest.SyncRestHandler.PrepareRequest(RequestParameters requestParameters, Object requestBody, String oauthRequestUri, Boolean includeRequestId) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.Core\RestCalls\SyncRestHandler.cs:line 85
   at Intuit.Ipp.QueryFilter.QueryService`1.ExecuteIdsQuery(String idsQuery, QueryOperationType queryOperationType) in C:\Users\nshrivastava\Documents\Git\QuickBooks-V3-DotNET-SDK\IPPDotNetDevKitCSV3\Code\Intuit.Ipp.QueryFilter\QueryService.cs:line 216

**Comment by nimisha84** [comment]
Can you elaborate more on what call you were trying to make? How can I replicate this issue? Which SDK version are you using?

**Comment by knopa** [comment]
I used latest version V14.6.1.0
Also has upgraded dependency
Serilog.Sinks.Console - 4.0.0
Serilog.Sinks.File - 5.0.0
Serilog.Sinks.Trace - 3.0.0
When downgraded them to 
Serilog.Sinks.Console - 3.1.1
Serilog.Sinks.File - 2.0.0
Serilog.Sinks.Trace - 2.0.0
I became works

**Comment by knopa** [comment]
Why not just use ILogger interface and move all logging to separate library for backward compatibility and keep main library without dependencies which always has issue with keep all libraries up to date

**Comment by nimisha84** [comment]
Hi @knopa,
Good suggestion. We have SDK maintenance work scheduled in Aug 1st week. Will see if this can be prioritized. If you can create a pull request for the same earlier, I will be happy to merge it. Either ways, I see you are unblocked for now. Thanks for posting the issue and the update.

Nimisha

**Comment by nicknguyen** [comment]
> Can you elaborate more on what call you were trying to make? How can I replicate this issue? Which SDK version are you using?

It's reproducible by upgrading the nuget package for Serilog.Sinks.File...namely Serilog to its latest version. It blows up here: OAuth2Client.GetAuthorizationURL(scopes);

**Comment by nimisha84** [comment]
HI Developers, 

Our SDK has some limitations wrt to which package versions it can support for net461, net472 and netstandard2.0 and therefore, we cannot upgrade serilog dependencies to latest or allow them to be updated as it will blow up the code due to the frameworks a certain dependency version can support. What @knopa suggested will not work as expected as we still have enabled certain sinks for all above frameworks and standard version and external dependencies will be be downloaded. Will be releasing a new SDK update soon and if you have additional suggestions, I would recommend raising a PR and we can merge.

Thanks,
Nimisha

**Comment by nimisha84** [comment]
New pre release out to support Custom Serilogger ILoggers - https://github.com/intuit/QuickBooks-V3-DotNET-SDK/releases/tag/14.6.2-Pre

**Comment by nimisha84** [comment]
If you have additional feedback, please submit a PR.

**Comment by redhorseck** [comment]
I have the same issue. I used latest version V14.6.1.0
I downgraded these dependencies
Serilog.Sinks.Console - 4.0.0 -> 3.1.1
Serilog.Sinks.File - 5.0.0 -> 2.0.0
Serilog.Sinks.Trace - 5.0.0 -> 2.0.0
Now it works. But this seems less than ideal. If the IppDotNetSdkForQuickBooksApiV3 installs/updates Serilog, the dll's it uses should work, no? Every time I update IppDontNet... will I have to downgrade Serilog?

**Comment by southernskip** [comment]
_Why not just use ILogger interface and move all logging to separate library for backward compatibility and keep main library without dependencies which always has issue with keep all libraries up to date_

100% this. Tried to do the downgrades redhorseck suggested and it downgraded the SDK to version 8.1. DLL Hell again

**Comment by nimisha84** [comment]
Unfortunately, we have to support to .Net 461,Net 472 and Standard 2.0 frameworks and therefore there are limitations on what dlls we can use. We earlier upgraded the serilog dlls in a release and found the bug with older version framework compatibility. Therefore, we had to downgrade those and continue to use the downgraded version in our newer versions too.

**Comment by fsfc1** [comment]
Hi @nimisha84 this continues to be a serious issue, please consider dropping support for older frameworks compatibility and allow us to keep Serilog up to date
