### ISSUE TITLE
Allow users to inject their own ILogger

### ISSUE THREAD

**Issue by sbyse** [intuit/QuickBooks-V3-DotNET-SDK#199]
When attempting to diagnose issues with the SDK it would be useful to be able to use our application's logger (via the ILogger interface) rather than having to enable the serilog file/console logging, neither of which are particularly useful when used in the cloud.

Rather than trying to cater for every use case I suggest allowing consumers of your library to pass in their own logger to the OAuth2Client and ServiceContext.

This would also have the benefit of removing the dependency issues mentioned in #198

**Comment by nimisha84** [comment]
Please submit a PR if you can and I will be happy to merge. Thanks for the feedback.

**Comment by nimisha84** [comment]
New pre release out to support Custom Serilogger ILoggers - https://github.com/intuit/QuickBooks-V3-DotNET-SDK/releases/tag/14.6.2-Pre

**Comment by nimisha84** [comment]
If you have additional feedback, please submit a PR
