### ISSUE TITLE
Line item rate not getting mapped

### ISSUE THREAD

**Issue by pula2000** [intuit/QuickBooks-V3-DotNET-SDK#2]
We're using the .NET sdk but when we look at the order page in quickbooks online, we don't see the rate value for the product getting populated. Can someone point to the right field within Intuit.Ipp.Data namespace that needs to be mapped because I can't find that field?? Thanks
![image](https://cloud.githubusercontent.com/assets/6827157/25402847/b3145a52-29bf-11e7-851e-d8cd1942fd7a.png)

**Comment by nimisha84** [comment]
Check this sample code-https://gist.github.com/IntuitDeveloperRelations/6500373

    lineSalesItemLineDetail.AnyIntuitObject = 33m;
    lineSalesItemLineDetail.ItemElementName = ItemChoiceType.UnitPrice;

**Comment by pula2000** [comment]
we generally are creating sales receipts rather than  invoices....will that code snippet be the same??

**Comment by nimisha84** [comment]
Yes same. Try creating txn directly in company file first. Then read it using API explorer.
Compare with your code or generated request log to correct your code.
Or refer docs to see what is the correct field that needs to be set.

There is a CRUD sample app too which you can refer-
https://github.com/IntuitDeveloper/SampleApp-CRUD-.Net
