### ISSUE TITLE
Invalid URI: The format of the URI could not be determined

### ISSUE THREAD

**Issue by scottiemc7** [intuit/QuickBooks-V3-DotNET-SDK#206]
When using `OAuth2Client`, setting a value other than "production" or "sandbox" for `environment` gives you the error message

`Invalid URI: The format of the URI could not be determined`

This is a really confusing message, considering the parameter before is `redirectURI`.

**Comment by rkasaraneni20** [comment]
Thanks @scottiemc7. Will make this change as part of the next release

**Comment by rkasaraneni20** [comment]
We updated the error message.
