### ISSUE TITLE
Error method not found serilog.FileLoggerConfigurationExtensions.File when upgrade to Serilog 5

### ISSUE THREAD

**Issue by krurkrit** [intuit/QuickBooks-V3-DotNET-SDK#207]
If I do not misunderstand the Nuget package "IppDotNetSdkForQuickBooksApiV3" use "Serilog.Sinks.File" v. 4.1.0, right?

Could you please provide the nuget package "IppDotNetSdkForQuickBooksApiV3" that build with Serilog v. 5?
or Do you have plan to update it?

My project use IppDotNetSdkForQuickBooksApiV3 v. 14.6.1 and work fine with Serilog.Sinks.File v. 4.1.0.
However, I updated Serilog to v.5 and it broke on runtime at GetBearerTokenAsync in Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.

I already investigated and found that Serilog add an optional parameter to method "serilog.FileLoggerConfigurationExtensions.File".

So, when IppDotNetSdkForQuickBooksApiV3 calls method "File" in Serilog, it expect Serilog will provide File with the number of parameters like v. 4.1.0 (15 parameters). But the adding an optional parameter in Serilog affect the method "File" with 15 parameters unavailable (because method "File" in Serilog v.5 has 16 parameters insteadly).

I know that should be "Serilog" problem, but they seem to not fix because it's major version for them.
So, I would like to know is it possible for "IppDotNetSdkForQuickBooksApiV3" package to work with Serilog v.5.

Thank you in advance.

**Comment by nimisha84** [comment]
You can get a local SDK version and update the Serilog dependency. We have constraints related ti supporting older .net frameworks- 4.6.1 and 4.7.2 and therefore need to keep using the existing serilog version
