### ISSUE TITLE
Intuit.Ipp.Data.dll File Version

### ISSUE THREAD

**Issue by mattimeo** [intuit/QuickBooks-V3-DotNET-SDK#208]
In v7.5 of this SDK Intuit.Ipp.Data.dll was versioned like the other dlls with 7.5.0.0, but now in the latest releases it is 1.0.0.0. I assume this is unintentional. I believe it should be versioned to match the other Intuit.Ipp dlls or at least be higher than its prior version. I made a workaround to get this to deploy with our internal updater utility so it saw the file as newer than the 7.5.0.0 version.

Currently:
![image](https://user-images.githubusercontent.com/1500267/137759762-62c2ad17-d2c6-45c6-8e1e-7a6a376652fe.png)

Back in v7.5 of this SDK:
![image](https://user-images.githubusercontent.com/1500267/137759824-b45e57aa-465d-4868-8776-a50ec8b98b74.png)

**Comment by nimisha84** [comment]
Thanks for bringing this up. Will fix it when we have the next release in about 2months

**Comment by rkasaraneni20** [comment]
We updated the dll version for Intuit.Ipp.Data. Thanks for bringing to our notice
