### ISSUE TITLE
IOException when log file for given Ticks already exists

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#21]
Occurs when you do parallel requests because of this line https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.Core/LogRequestsToDisk.cs#L93

it is safe to use `FileMode.Append` instead (other option - overwrite - will hide some data)

**Comment by nimisha84** [comment]
Can you please make the change and send a pull request?
