### ISSUE TITLE
How do you download attachments?

### ISSUE THREAD

**Issue by TonyValenti** [intuit/QuickBooks-V3-DotNET-SDK#211]
Some entities, such as invoices or contacts, can have attachemnts linked to them.

How do I download these attachments?

**Comment by nimisha84** [comment]
You can check this code-
https://github.com/IntuitDeveloper/SampleApp-CRUD_.Net_Oauth2/blob/master/SampleApp_CRUD_.Net/SampleApp_CRUD_.Net/Entities/Supporting%20Entities/Attachable.cs

**Comment by TonyValenti** [comment]
@nimisha84 Thanks so much!  This was exactly what I needed!
