### ISSUE TITLE
QBO issue, not related to this project per se but I don't have a social media account to get anyone's attention so...

### ISSUE THREAD

**Issue by jsma** [intuit/QuickBooks-V3-DotNET-SDK#223]
First, apologies. I know this has nothing to do with the DotNET SDK but as far as I can tell, the only avenue of contact is the feedback site which is indistinguishable from a black hole where customer feedback can safely be ignored.

The issue is that the QBO _website_ does not allow people to enter their VALID name, the same VALID name that is accepted by their bank, credit card company, etc. but because some developer/engineer at Intuit once upon a time instituted a goofy validation rule on the input form this is their user experience:

<img width="568" alt="Screen Shot 2022-04-01 at 4 08 36 PM" src="https://user-images.githubusercontent.com/24574/161353433-24b7e42f-01b2-486e-aff4-64249a0c66f9.png">

If I remove nothing more than a hyphen (which is not my VALID/legal first name!), I can get the payment submitted and then I see this link on the confirmation page:

<img width="449" alt="Screen Shot 2022-04-01 at 4 22 03 PM" src="https://user-images.githubusercontent.com/24574/161353706-e3dc8010-1f49-4c5e-99d7-1b6c148c0b1d.png">

If you go to the [feedback site and search for "hyphen"](https://feedback.qbo.intuit.com/forums/591862?query=hyphen), you'll see there are a lot of insulted people dealing with this:

![Screenshot 2022-04-01 at 16-13-52 QuickBooks Invoice Payments Portal Hot (10874 ideas) – Customer Feedback for QuickBooks Online](https://user-images.githubusercontent.com/24574/161353446-efbfce86-8716-4a56-953e-6ece3e36c670.png)

Again, I know the DotNET team is not necessarily directly responsible for this but it's simply unacceptable to have web forms that impose arbitrary rules on what is a "name" in the year of our lord 2022. It's also unacceptable to have a customer feedback portal that is completely ignored. Please escalate internally and get this addressed.

Unfortunately I did not use my browser's debug tools to figure out what Javascript validation rules are in effect, but whatever they happen to be, they are dumb and should be deleted. The back-end server should handle rejecting SQL-injection etc without causing client-side user experience issues for actual human beings entering their actual human names. 

Thanks!

**Comment by nimisha84** [comment]
Closing old issue!
