### ISSUE TITLE
Can I get confirmation on 'quickbooks.api.intuit.com' BaseUrl in samples

### ISSUE THREAD

**Issue by brcaswell** [intuit/QuickBooks-V3-DotNET-SDK#226]
Can I get confirmation on these BaseUrls.  I feel like they are outdated.

https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/b6b27835b6f7ac537e4e3cd8d7c9e4926e63fb66/IPPDotNetDevKitCSV3/Sample%20app%20for%20testing%20SDK/OAuth2/MvcCodeFlowClientManual/Web.config#L24

more specifically, is it supposed to be https://developer.api.intuit.com/ ?  which seems to correlate to a discovery document and service endpoint: https://developer.api.intuit.com/.well-known/openid_configuration and https://developer.api.intuit.com/.well-known/openid_sandbox_configuration (depending on the environment specified in client type), respectfully

**Comment by nimisha84** [comment]
The base urls are correct for qbo api calls. What you are looking at is the oauth base urls. Both are supposed to be different
