### ISSUE TITLE
Version 999.9.9.9 of IppDotNetSdkForQuickBooksApiV3 on nuget

### ISSUE THREAD

**Issue by czietsman** [intuit/QuickBooks-V3-DotNET-SDK#228]
Hi

This looks very suspect to me, or did something go wrong during build / publishing? Is it possible that someone got hacked?

![image](https://user-images.githubusercontent.com/396202/169272802-d934164a-6e05-4f69-9736-61c7c1babe6e.png)

**Comment by nimisha84** [comment]
That is weird, let me check and unpublish it. Thanks a lot for giving the feedback

**Comment by nimisha84** [comment]
I see it is unlisted and was test package created long back. I have deprecated it. Not sure how you are able to view it.

**Comment by robin-huss** [comment]
Still showing as 999.9.9.9 in Visual Studio so it seems unlisting / depricating it does not work. Furthermore: Visual Studio is now actually warning me this package is depricated even though i'm not using 99.9.9.9. Not great :(

![image](https://user-images.githubusercontent.com/26572475/172414468-df873741-289e-4cb9-8a9c-8a9e1a8d2e58.png)

**Comment by nimisha84** [comment]
Hmm.... so not sure why visual studio is acting weird. Which version of VS are you using? You can check with MS support but from our end, we have definitely unlisted and deprecated this version.

**Comment by nimisha84** [comment]
Are u checking in the installed nuget packages? That tab will show the version if u had it installed already. On the nuget package ->first tab where you search for all packages, try that screen and this should not show up to install now atleast

**Comment by robin-huss** [comment]
Ok, it seems there is something weird going on at our end after all.

The 999 version is indeed unlisted and not visible anymore when checking using nuget.org as the only source (even though in my screenshot it specifically says nuget.org in the top right?!). I have a second source specified using Azure DevOps Artifacts. That source somehow still has the 999 version listed even though i cannot find this version when browsing manually.. weird. I'll look into this and see what i can do to get this fixed.

Thanks for looking into this!

**Comment by czietsman** [comment]
We also use Azure DevOps as our primary feed and nuget as an upstream feed. DevOps would cache the packages you use to mitigate against service outages and takedowns by package authors. I suspect you will need to unlisted it in Azure DevOps as well.
