### ISSUE TITLE
FindAllAsync returns empty list

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [intuit/QuickBooks-V3-DotNET-SDK#23]
I tried with customers and bills and it seems to happen no matter what.

Calling `FindAll` works:
![image](https://user-images.githubusercontent.com/14170257/34837051-a07a74dc-f6c7-11e7-9f30-91323e6b5a4c.png)

But when `FindAllAsync` returns it does not have any data:
![image](https://user-images.githubusercontent.com/14170257/34837139-e5a97120-f6c7-11e7-877c-f5e6d43e0dba.png)

The logs show a huge response that somehow doesn't make it to the async callback:
![image](https://user-images.githubusercontent.com/14170257/34837228-1a122f24-f6c8-11e7-81af-56747214e882.png)

Trace logs look pretty normal:
![image](https://user-images.githubusercontent.com/14170257/34837351-817c27aa-f6c8-11e7-943a-12b855666299.png)

A couple other people seem to have had this issue as well:
https://help.developer.intuit.com/s/question/0D5G000004Dk723KAB/data-service-async-call-doesnt-respond-entities
https://help.developer.intuit.com/s/question/0D50f00004zqoZwCAI/findallasync-for-customer-doesnt-work-properly-c

On the second one @nimisha84 mentioned a question here on GitHub but I can't seem to locate that question.

**Comment by diana-derose** [comment]
Hi Jesse - I have reported this to the team to take a look at it, here is the bug id (SDK-632) for your reference. We'll keep you posted.

**Comment by nbhambhani** [comment]
Hi Jesse,
The fix for this will be available in the next release during mid-Feb. Thanks for reporting this.
