### ISSUE TITLE
Missing Fields

### ISSUE THREAD

**Issue by steveschmitt** [intuit/QuickBooks-V3-DotNET-SDK#231]
The entity definitions are missing some fields that are in the API Explorer.

**Term** - missing [DueDays](https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/term)

There are others.

I'm using version [14.6.3.2 from Nuget](https://www.nuget.org/packages/ippdotnetsdkforquickbooksapiv3), on .NET Standard 2.0.

Term is also missing `DueDays` in the [.NET SDK 4.0.0 Documentation](https://static.developer.intuit.com/sdkdocs/qbv3doc/ippdotnetdevkitv3/html/1d49485d-be26-bac2-388f-98864206a506.htm)

SDK, docs, and API Explorer are not in sync.

**Comment by nimisha84** [comment]
Let me know if u still need help with the use of DueDays but the doc link above is a very old deprecated one. We don't support the static docs for the SDK since many years now as not many devs referred them.

**Comment by allaineg-cw** [comment]
Hello, we are trying to get the DueDays as well for Term but it seems not accessible/available
