### ISSUE TITLE
CDCAsyncCompleted returns ArgumentException when more than one entity is changed

### ISSUE THREAD

**Issue by jlddodger** [intuit/QuickBooks-V3-DotNET-SDK#24]
Hi.

I am getting an ArgumentException when calling DataService.CDCAsync.

Intuit.Ipp.Exception.IdsException: An item with the same key has already been added.

This seems to happen due a difference between the synchronous CDC call and the asynchronous CDCAsync handler.  When multiple entities of a common type are returned by the CDC, the repeated add into the returnValue Dictionary causes the error.

CDCAsync (causes error)

```
	object[] tempEntityArray = (object[])tempEntities;

	if (tempEntityArray.Length > 0)
	{
		foreach (object item in tempEntityArray)
		{
			entities.Add((IEntity)item);
			returnValue.Add(item.GetType().Name, entities);
			count++; // this line appears unused
		}
	}
```

CDC (works correctly)
```
	object[] tempEntityArray = (object[])tempEntities;

	if (tempEntityArray.Length > 0)
	{
		List<IEntity> arr = new List<IEntity>(); // this line appears unused
		string entityName = string.Empty;
		foreach (object item in tempEntityArray)
		{
			entities.Add((IEntity)item);
			entityName = item.GetType().Name;
		}
		returnValue.entities.Add(entityName, entities);
	}
```

**Comment by nbhambhani** [comment]
Hi - I have reported this to the team to take a look at it, here is the bug id (SDK-634) for your reference. We'll keep you posted.

**Comment by jlddodger** [comment]
Thanks for the update.
