### ISSUE TITLE
Question: How to build?

### ISSUE THREAD

**Issue by kvasserman** [intuit/QuickBooks-V3-DotNET-SDK#27]
I have question. How do you build this solution? Are there instructions somewhere on how to build it? I downloaded the source and can't build it in VS2017 because of multiple circular references. For example Ipp.Rety references Ipp.Core and Ipp.Core references Ipp.Retry and many others like that. What am I missing?

**Comment by nbhambhani** [comment]
Hi, Are the references in your solution all resolved? Please copy screenshots of the error and share them here.

**Comment by sm-g** [comment]
duplicate: https://github.com/intuit/QuickBooks-V3-DotNET-SDK/issues/14
