### ISSUE TITLE
NuGet package no longer lists Newtonsoft.Json as a dependency, but it's still required

### ISSUE THREAD

**Issue by dahanc** [intuit/QuickBooks-V3-DotNET-SDK#302]
Version 14.6.3.4 of the NuGet package [doesn't list Newtonsoft.Json](https://www.nuget.org/packages/IppDotNetSdkForQuickBooksApiV3/14.6.3.4#dependencies-body-tab) as a dependency (14.6.3.3 and previous versions do), but Intuit.Ipp.Utility assembly still needs it. And according to IL DASM, it's referencing Newtonsoft.Json 9.0.0.0, despite the commit saying "Updating NewtonJson version to 13.0.2"

Now, my project, which had been working fine with 14.6.3.2, throws a System.IO.FileNotFoundException when calling ExecuteIdsQuery(): Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The system cannot find the file specified.

**Comment by sujitharamadass** [comment]
@dahanc We will fix this in the upcoming release

**Comment by sujitharamadass** [comment]
This is fixed in the latest release 14.6.3.5
