### ISSUE TITLE
Many Unicode characters don't work correctly

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [intuit/QuickBooks-V3-DotNET-SDK#32]
.NET internally stores strings encoded as UTF-16 but QBO expects UTF-8. The two encodings are the same for all single-byte code points so you tend not to notice when you aren't sending special characters to QBO. But, for queries with special characters you must put all strings through the following filter (I wrote it as an extension method for kicks):
```csharp
        public static string ToUtf8(this string input) =>
            new string(Encoding.UTF8.GetBytes(input).Select(b => (char)b).ToArray());
```
Following the principle of least astonishment, this should be done by the SDK.

**Comment by AndrewShitsko** [comment]
Hello @Jesse-Hufstetler ​ . I would like to get some clarifications about your solution. You create customer with company name like "你好嗎", then using your code (by applying your extension to that unparsable value, result value will be like "ä½ å¥½å") you can query customer by processed company name string?

**Comment by Jesse-Hufstetler** [comment]
@AndrewShitsko Yes, if your customer's company name was in chinese you'd need to query by a gibberish string like that to get the customer.

**Comment by corneliutusnea** [comment]
This does not seem to work when used in a query.
E.g. I have a customer in QBO "Geo ăâîșşțţ". Using the above conversion I get "Geo ÄÃ¢Ã®ÈÅÈÅ£".
However doing "select * from Customer where DisplayName  = 'Geo ÄÃ¢Ã®ÈÅÈÅ£'" does not find the customer.

I think these issues are related:
https://intuitdevelopergroup.uservoice.com/forums/182764-intuit-developer-group/suggestions/33572257-full-unicode-support-for-query

https://help.developer.intuit.com/s/question/0D50f00005GO6YlCAL/how-to-query-unicode-characters

**Comment by AndrewShitsko** [comment]
@corneliutusnea the same result for me as well.

**Comment by nimisha84** [comment]
Currently this is not supported. If your search value has unicode then for now, the only way is to do a select * from entity query and get the full resultset and then use looping to match the value you need.
We do have an enhancement req open for this for supporting this in v4

**Comment by andrew-from-toronto** [comment]
Seeing as v4 seems to no longer be planned, should this be reconsidered? This is still an issue today.
