### ISSUE TITLE
Question about unused exceptions

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#34]
I want to properly handle all possible exception from SDK, but some of them never used in code:

- FaultException https://github.com/intuit/QuickBooks-V3-DotNET-SDK/search?utf8=%E2%9C%93&q=FaultException&type=
- ServiceReturnedNoInformationException https://github.com/intuit/QuickBooks-V3-DotNET-SDK/search?utf8=%E2%9C%93&q=ServiceReturnedNoInformationException&type=
- ServerTooBusyException https://github.com/intuit/QuickBooks-V3-DotNET-SDK/search?utf8=%E2%9C%93&q=ServerTooBusyException&type=
- ProtocolException https://github.com/intuit/QuickBooks-V3-DotNET-SDK/search?utf8=%E2%9C%93&q=ProtocolException&type= (this catched, but never thrown)
- InvalidServiceRequestException https://github.com/intuit/QuickBooks-V3-DotNET-SDK/search?utf8=%E2%9C%93&q=InvalidServiceRequestException&type=

Are they all was used before, but will not be used in future?

**Comment by nimisha84** [comment]
They might be used in future but not yet. I believe FaultException and ProtocolExceptions are valid ones but will have to see the code more to see why they were never thrown. My windows VM is corrupt right now. Give me sometime and I will get back to you on this.

**Comment by nimisha84** [comment]
You are right. We always throw the IdsException with status code. The above exceptions are not thrown but were implemented as a part of the initial design. You can check Faulthandler.cs class to check the details.
Sorry, was not able to confirm earlier.
