### ISSUE TITLE
Append access can be requested only in write-only mode.

### ISSUE THREAD

**Issue by kdubious** [intuit/QuickBooks-V3-DotNET-SDK#38]
I get an error `Append access can be requested only in write-only mode.` with the following set to true:
`	<intuit>
		<ipp>
			<logger>
				
				<requestLog enableRequestResponseLogging="true" requestResponseLoggingDirectory="Z:\WWW\PM\Logs"
				xdt:Transform="Replace"/>
			</logger>
		</ipp>
	</intuit>
	<intuit>
		<ipp>
			<logger>
				
				<requestLog enableRequestResponseLogging="true" requestResponseLoggingDirectory="Z:\WWW\PM\Logs"
				xdt:Transform="Replace"/>
			</logger>
		</ipp>
	</intuit>`

**Comment by nimisha84** [comment]
Do you not have write access to the directory to which you are writing the logs? Can you try using the latest SDK nuget package and try this again?

**Comment by kdubious** [comment]
@nimisha84 Everything was working fine in an older version of the SDK. But then I did an upgrade (to the latest), and started getting this message.

In the old version, every request/response was its own file. The error makes it sound like your opening the file in read-write, and requesting append access? Did something change?

**Comment by nimisha84** [comment]
Yes, we had merged a pull request for this recently-
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/pull/33

**Comment by kdubious** [comment]
So what do you suggest I do? At the moment, I have logging disabled.

**Comment by nimisha84** [comment]
Right click on Z:\WWW\PM\Logs and make sure you do not have readonly checked. Remove the check on the folder and then retry logging

**Comment by kdubious** [comment]
Z:\WWW\PM\Logs is a folder, it's not readonly. There's nothing in it right now.
The App Pool user has Modify permissions.
My Intuit.Ipp.*.dll files are Version 5.2.0.0.

I'm still getting the same error.

**Comment by kdubious** [comment]
Any ideas why this still fails?

**Comment by nimisha84** [comment]
Sorry, have been really busy with stuff. I see the fix suggested above in PR#33 was just a suggestion. I will look into adding the fix suggested with fileshare in next release.But, still, your issue does not seems to be related to it. Might need to try out diff things to replicate this. Do you have a test project where I can replicate this issue. If so, then please share it on google drive or dropbox

**Comment by kdubious** [comment]
@nimisha84 Can you send me the "standard" web config settings? It looks like the error is complaining about opening a file requesting "Append" mode, and it's being done as "read-write", not write only. I can't easily create a test bed from my project, but it seems the issue would fail universally. Or, that I have the wrong config. My code worked against the older version of your SDK, so I wonder if I need to change something in my code / config to get back in sync with your new code?

**Comment by kdubious** [comment]
@nimisha84 Any update?

**Comment by nimisha84** [comment]
This was fixed in our last SDK release! 

Thanks,
Nimisha
