### ISSUE TITLE
Intuit.Ipp.Retry dll not copied to output bin in 5.2.0

### ISSUE THREAD

**Issue by oflahero** [intuit/QuickBooks-V3-DotNET-SDK#39]
Hi - since I upgraded the Nuget package to 5.2, I found that Intuit.Ipp.Retry.dll was not being copied along to the output exe folder of my project, and so I consistently get a runtime failure on running a report (ReportService.ExecuteReport, say).

`System.IO.FileNotFoundException: Could not load file or assembly 'Intuit.Ipp.Retry, Version=5.1.2.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.`

It was OK up to now - have I missed something I'm supposed to be doing since the upgrade? Or is this some crazy Nuget thing?

**Comment by oflahero** [comment]
Is there a possibility that this DLL will not get copied over unless there is a <retry> section in the <ipp> config? Long shot I know but this was part of quite a few Nuget updates I performed, and you never know what Roslyn is doing when it does its compiler/linker magic.

**Comment by oflahero** [comment]
Self-replying to previous comment: no, not relevant. Still investigating.

**Comment by nimisha84** [comment]
I have tried to reproduce this issue but could not. Seems to me a dll hell issue with the previous build and this one.
Please delete all references for the nuget package and remove from ref from packages.json and reinstall the Nuget package. See if that resolves the issue.

**Comment by oflahero** [comment]
Thanks Nimisha. DLL hell is right. 

I fixed my issue by adding the Nuget package to the top-level project. IppDotNetSdk was being used by an Azure WebJob via a shared DLL, and so was only referenced in the DLL. This was fine up to 5.2, though you never know with DLL hell what exactly sends everything out of balance.

By adding a reference to the WebJob itself also - the 'console' EXE project - it's now OK. It's funny that only the 'retry' DLL wasn't copied previously - all the other Ipp*.dlls were present.

Anyway, I hope this may help some random desperate googling person sometime! I'll close this now. Thanks for having a look.

**Comment by nimisha84** [comment]
Thanks for the feedback. Let me see if I can fix this issue somehow in next release.

**Comment by MatthewSteeples** [comment]
@oflahero We've hit this problem too just now

**Comment by oflahero** [comment]
Did the fix I mentioned above work for you?

Just to note also: I noticed that a different Ipp*.dll was missing in a different project, pre-fix. So it's not just limited to the 'retry'. DLL.

**Comment by oflahero** [comment]
Ah, that warm fuzzy feeling of knowing all those keystrokes weren't in vain!
