### ISSUE TITLE
SELECT Count(*) query not supported

### ISSUE THREAD

**Issue by evillegas92** [intuit/QuickBooks-V3-DotNET-SDK#42]
Hi, first of all thanks for doing a great job with this SDK.

I can't however find a way to get the `totalCount` response from the query endpoint using the Batch.Execute() method, when passing in a query that has a SELECT Count(*) clause. Am I going about this the wrong way?

Here's the full code I use:
`Batch batch = ConnectionCache.GetQBODataService(qboCredentials).CreateNewBatch();
				batch.Add(query, batchId);
				batch.Execute();

				if (batch.IntuitBatchItemResponses != null && batch.IntuitBatchItemResponses.Count() > 0)
				{
					IntuitBatchResponse response = batch.IntuitBatchItemResponses.FirstOrDefault(item => item.Id == batchId);`

IntuitBatchResponse has a response but the response has Entity = null and Entities.Count = 0. No other property with the totalCount from the QuickBooks response. See image from Fiddler
![count_query](https://user-images.githubusercontent.com/26449627/44167172-118ead80-a093-11e8-8f0f-62dc511c519e.JPG)
 attached.

**Comment by nimisha84** [comment]
Looks like a bug to me. Thanks for the feedback, we will look into this and fix it in our next release.

**Comment by nimisha84** [comment]
In the 5.3 SDK release, can you try this code?
Batch batch = commonServiceQBO.CreateNewBatch();
                   

                    batch.Add("select * from Account startPosition 0 maxResults 10", "queryAccount");
                    batch.Execute();

                    if (batch.IntuitBatchItemResponses != null && batch.IntuitBatchItemResponses.Count() > 0)
                    {
                        IntuitBatchResponse res = batch.IntuitBatchItemResponses.FirstOrDefault();
                        List<Account> acc = res.Entities.ToList().ConvertAll(item => item as Account);
                    };

**Comment by nimisha84** [comment]
We don't support LINQ detailed extensions as we deprecated them earlier due to some issues. Some simpler ones like the one I suggested above works.

**Comment by evillegas92** [comment]
Hi @nimisha84 
I don't see how this query you suggested 

> select * from Account startPosition 0 maxResults 10

Has anything to do with SELECT Count( *). I also don't see what LinQ detailed extensions have to do with SELECT Count( *) either.

Will I be able to get the _totalCount_ value from the SELECT Count( *) query in the next release? If so, what release would that be? 5.4?

Thanks.

**Comment by nimisha84** [comment]
I might have misunderstood your query earlier thinking the count was required for the batch itemresponse and not the actual count query. I mentioned linq as I saw you used this-FirstOrDefault(item => item.Id == batchId);

I am looking at this issue again and hopefully should be able to fix this in 5.4 unless any other high priority issues come up. Will keep you posted.
Thanks for the feedback.

Also, I would like to understand why you would want to call count query in batch and not as a regular query instead? Is there a specific use case?

**Comment by evillegas92** [comment]
How would I call count query in a regular query using the SDK? The only way I've found to execute a custom query is through Intuit.Ipp.DataService.Batch.

Thanks for re opening the issue.

**Comment by nimisha84** [comment]
DataService commonServiceQBO = new DataService(serviceContext);
                   
                    QueryService<Invoice> inService = new QueryService<Invoice>(serviceContext);
                    var In = inService.ExecuteIdsQuery("SELECT count(*) FROM Invoice");

or int count= inService.ExecuteIdsQuery("SELECT count(*) FROM Invoice").Count();

**Comment by nimisha84** [comment]
ExecuteIdsQuery should work for any queries.

**Comment by evillegas92** [comment]
Thank you @nimisha84 this is actually what I needed.
`int count= inService.ExecuteIdsQuery("SELECT count(*) FROM Invoice").Count();`

I thought Batch was the only way to execute custom queries.

**Comment by nimisha84** [comment]
Ok great. Anyways, I have fixed the SDK to return count in batch too. Will be available in 5.4 version of SDK in a week or two.
