### ISSUE TITLE
Suspected License Violation

### ISSUE THREAD

**Issue by brockallen** [intuit/QuickBooks-V3-DotNET-SDK#43]
Hello, my name is Brock Allen and I am the co-author/co-owner of the IdentityModel project, whose main repository resides here https://github.com/IdentityModel/IdentityModel2.

It has come to my attention that a commit to this repository, controlled by Intuit, seems to contain files that were originally from the IdentityModel2 project. The manner in which the files were copied and modified violates the license of the IdentityModel2 project (as well as copyrights held by Microsoft included in the IdentityModel2 project). The commit to this repository is here:

https://github.com/intuit/QuickBooks-V3-DotNET-SDK/commit/c1ce13d65345cb46d42d342bbc61513bf6dc1546

While the files do not match exactly those from the IdentityModel2 project, there are many striking similarities such as directory structure, file names, executable source code, unit tests, and code comments that are an exact match. The modifications performed to the original files are mostly cosmetic and include namespace changes, variable name changes, rewording comments, and replacing the copyright ownership notices themselves. Below are two file diffs that illustrate some of these similarities and modifications.

![untitled0](https://user-images.githubusercontent.com/649492/44302044-a55cb580-a2ef-11e8-8d48-283c7b16b381.png)
![untitled1](https://user-images.githubusercontent.com/649492/44302045-a7bf0f80-a2ef-11e8-8c1e-5e03947e69f2.png)

While IdentityModel2 uses the Apache 2 license, which is a permissive free software license, it does state in sections 4b and 4c (https://github.com/IdentityModel/IdentityModel2/blob/dev/LICENSE#L97-L104) that:

  * You must cause any modified files to carry prominent notices stating that You changed the files
  * You must retain, in the Source form of any Derivative Works that You distribute, all copyright, patent, trademark, and attribution notices from the Source form of the Work, excluding those notices that do not pertain to any part of the Derivative Works

On behalf of the owners of the IdentityModel project, I kindly request that Intuit remedy this copyright violation by either removing the files, or by adhering to the license agreement.

// @leastprivilege @jongalloway @shanselman

**Comment by nimisha84** [comment]
HI @brockallen - We didn't mean to leave off the copyright and we will open up an issue with open source identity team to address it. Meanwhile, I have updated the files even the modified, added one to include the Licensing from IdentityModel2 repo. 

Thanks,
Nimisha

**Comment by brockallen** [comment]
Thank you for following up on this. 

I think moving forward we want to understand what in IdentityModel was blocking you in the first place. Did you open any issues in our repo asking for enhancements? I would think that's the best approach: 1) let us know what might need changing to support your scenario, and 2) then you should be referencing our library via the nuget package rather than copying the source code. 

If that was done originally, then this issue could have been avoided.

**Comment by IntuitDeveloperRelations** [comment]
Hi @brockallen, 
Intuit mistakenly published this library without the copyright notice. This was an oversight on our part, and the result of a misunderstanding of the open source licensing process by our team. We fully support the open source community and regret our error.

The issue has been corrected here: https://github.com/intuit/QuickBooks-V3-DotNET-SDK/commit/506b872f7ae3f22eab153f460e703c095bd00864#diff-68341b3e1ed04a5b6a86868254db097d 

regards
Jarred Keneally
Director, Intuit Developer Relations

**Comment by nimisha84** [comment]
Hi @brockallen - I will setup a call with you in a week's time to go over the changes we did for the Intuit's implementation as it was limited to just server side Oauth2 support and having some additional params like realm/company id support. Hopefully you could help us with the questions then and suggest what best we can do to handle those using your binaries instead.

**Comment by brockallen** [comment]
Were you able to finally get all your questions/features covered with IdentityModel? If so, then were you able to get the code to reuse IdentityModel as a NuGet, which is preferable to copying the code in?

**Comment by nimisha84** [comment]
Yes, I was able to get all my questions answered. However, I am currently on maternity leave for 3 weeks. Once I return back, I will give you an update on the release for the Oauth2 lib using the binaries. Thanks for all the help.

**Comment by brockallen** [comment]
Ok, thanks for the update. 

And congratulations!

**Comment by nimisha84** [comment]
Hi @brockallen,
We discussed with @leastprivilege here-

**Comment by brockallen** [comment]
Fair enough. Thanks for the updates to restore the copyrights and honor the license.
