### ISSUE TITLE
Can IntuitBatchResponse.Exception contain only ValidationException or not?

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#44]
`Batch` use [`IterateFaultAndPrepareException()`](https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.DataService/Batch.cs#L486) - copypaste from `FaultHandler` - to prepare exceptions from separate `BatchItemResponse`s.

From source code  it is obvious that `IntuitBatchResponse.Exception` could contain Service and Auth exceptions. But isn't such exception would be thrown during execution of batch, at [`restHandler.GetResponse(request);`](https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.DataService/Batch.cs#L416)?

**Comment by nimisha84** [comment]
You are right it should but as I mentioned previously, we throw IdsException as base from the SDK and parse other exceptions to it. Any service or auth exception all upstream exceptions move down to QBO apis and are thrown from the QBO api. You will not receive them separately but only through QBO API as IdsException using the .Net SDK.
