### ISSUE TITLE
Some bad .NET code in SampleApp-Dotnet_Payments app

### ISSUE THREAD

**Issue by swdenton** [intuit/QuickBooks-V3-DotNET-SDK#45]
remove lines 331-333 as they are not method parameters

        /// <param name="realmId"></param>
        /// <param name="access_token"></param>
        /// <param name="refresh_token"></param>

line 347 is testing for if (dictionary["access_token"] != null), but param is defined elsewhere (e.g. lines 216-219).  Failure to do this results in error "The given key was not present in the dictionary." when sample app is unzipped and configured for the first time.

**Comment by nimisha84** [comment]
Thanks for the feedback, will update the code and get back to you.
