### ISSUE TITLE
Invalid max batch items number?

### ISSUE THREAD

**Issue by sm-g** [intuit/QuickBooks-V3-DotNET-SDK#46]
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.DataService/Batch.cs has value "25" as max allowed batch items.

Why this value used? Here is no such value https://developer.intuit.com/docs/api/accounting/batch

**Comment by nimisha84** [comment]
It was the limit allowed by the API team earlier for batch payloads. It was later reduced to 10 as mentioned in the docs. However, we would not want to break any existing apps using the SDK with 25 requests in batch payload. So, we kept is as is.
