### ISSUE TITLE
Change internal references from binary to project

### ISSUE THREAD

**Issue by phatcher** [intuit/QuickBooks-V3-DotNET-SDK#48]
What is the rationale of using binary references within the project definitions e.g.
```
<Reference Include="Intuit.Ipp.Core, Version=5.0.0.0, Culture=neutral, processorArchitecture=MSIL">
    <SpecificVersion>False</SpecificVersion>
    <HintPath>..\..\SDK Assemblies\Intuit.Ipp.Core.dll</HintPath>
</Reference>
```
It makes compiling the SDK a nightmare with a lot of workarounds, you are shipping the entire library as one nuget package anyway so it can't be dependency versioning?

**Comment by nimisha84** [comment]
You are right. It shouldn't be there in the released version of open sourced SDK code.
The prob is that SDK has circular references and for the first build to work, we need the NUget package to get the project to build to and then we reference the dlls which are internally available on the SDK Assemblies folder. This nuget package reference is then removed. However, this might have been left in this version of SDK release by mistake and we will remove them in future.
We would also want to resolve SDK circular reference issues but it might lead to breaking the client apps and therefore we have never gone down that path. Let me know if it helps.

**Comment by phatcher** [comment]
@nimisha84 The more fundamental question is why you need circular references, given that it's basically a wrapper calling a REST API.

One way forward for the next version would be to identify the circularity (I'm presuming its to do with data structures) and lift those out to a contract assembly.

My original issue was trying to see why a port to .NET Standard would be difficult, but when I couldn't even compile the code it doesn't inspire much confidence.

**Comment by nimisha84** [comment]
Great point and feedback @phatcher - We would really love to spend some time on this initial design of the V3 SDK which was done years ago and fix the circular ref issues. We had tried to to do this in past too but due to diff priority bugs and releases coming in, we never got to the point of identifying the issues. Even for the next few releases we are tied up for QBC releases and V4 SDK in progress work. So, I would track your feedback for now to fix this as soon as we can. Meanwhile, we would love your support if you can help in resolving the circular ref issue by creating a PR.  In any case, thanks for whatever suggestions and support you provide.

**Comment by phatcher** [comment]
@nimisha84 Would you mind if I update the projects to VS2017 format, makes the referencing a lot easier and should simplify your nuget package creation process?

**Comment by nimisha84** [comment]
Please go ahead by creating a branch. Thanks!

**Comment by nimisha84** [comment]
Please feel free to reopen when you would like to discuss further on the changes you will be making. Thanks!

**Comment by nimisha84** [comment]
We are working on releasing the beta version of our DLLS for .net standard which you can use with .Net Core 2.1 projects.
Please let me know if you are interested in testing those out and giving us your feedback if you see any issues.

Thanks,
Nimisha

**Comment by nimisha84** [comment]
Please reply with your email ids, in case you are interested. I can send the zipped SDK dlls and steps to download any additional dependencies from Nuget. Later, in a few weeks when we release it, we will be releasing the NUget package with required dependencies.

**Comment by phatcher** [comment]
@nimisha84 Have you resolved the circular dependency issue in the new version?

My branch did this, but the open question was whether my approach would be acceptable.

**Comment by nimisha84** [comment]
Yes, we resolved it a few releases back already so that we could start the work on .Net Standard migration.

**Comment by nimisha84** [comment]
You can search for this package in pre-release on Nuget-
IppDotNetSdkForQuickBooksApiV3_NetStandard2_0 7.5.1-beta (for FULL v3 SDK), IntuitOAuth2PlatformClient_NetStandard2_0 7.5.1-beta (for just Oauth2 SDK).
"Ignore the warning that you get that package was restored using 4.6.1."

Use this appsettings.json as a reference for your .Net Core projects-
{
"Logger": {
"RequestLog": {
"EnableLogs": "false",
"LogDirectory": ""
}
},
//not supported added for backward compatibility
"CustomLogger": {
"RequestLog": {
"Enable": "false",
"Name": "",
"Type": ""
}
},
"Security": {
"Mode": {
"Oauth": {
"Enable": "false",
"AccessToken": ""
},
//not supported added for backward compatibility
"Custom": {
"Enable": "false",
"Name": "",
"Type": "",
"Params": ""
}
}
},
"Message": {
"Request": {
"CompressionFormat": "None",
"SerializationFormat": "Json"
},
"Response": {
"CompressionFormat": "None",
"SerializationFormat": "Json"
}
},
"Service": {
"BaseUrl": {
"Qbo": "",
"Ips": "", //not supported added for backward compatibility
"OAuthAccessTokenUrl": "", //not supported added for backward compatibility
"UserNameAuthentication": "" //not supported added for backward compatibility
},
"MinorVersion": {
"Qbo": "37"
}
},
"WebhooksService": {
"VerifierToken": {
"Value": ""
}
},
"Retry": {
"Mode": {
"LinearRetry": {
"Enable": "false",
"RetryCount": "",
"RetryInterval": ""
},
"IncrementalRetry": {
"Enable": "false",
"RetryCount": "",
"InitialInterval": "",
"Increment": ""
},
"ExponentialRetry": {
"Enable": "true",
"RetryCount": "",
"MinBackoff": "",
"MaxBackoff": "",
"DeltaBackoff": ""
}
}
}
}
 If you need 4.7.2 dlls generated by this .NET Standard v3 SDK, I can share those in a zip file.

**Comment by nimisha84** [comment]
Please test with this Nuget Package going forward-

IppDotNetSdkForQuickBooksApiV3 -> 7.5.0.3-beta
