### ISSUE TITLE
Method not found: 'System.Net.HttpWebRequest Intuit.Ipp.Core.Rest.IRestHandler.PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters, System.Object, System.String)'.

### ISSUE THREAD

**Issue by jeffhee** [intuit/QuickBooks-V3-DotNET-SDK#49]
We've discovered this very unusual issue using version 5.5 of this project from nuget.

The following code works locally:

           
```
            ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; //Add this just to be sure to use TLS1.2 
            realmId = Session["realm"].ToString();
            accessToken = Session["accessToken"].ToString();
            accessTokenSecret = Session["accessTokenSecret"].ToString();
            consumerKey = ConfigurationManager.AppSettings["consumerKey"].ToString();
            consumerSecret = ConfigurationManager.AppSettings["consumerSecret"].ToString();
            dataSourcetype = Session["dataSource"].ToString().ToLower();

            try
            {
                var intuitServicesType = new IntuitServicesType();
                        intuitServicesType = IntuitServicesType.QBO;

                var oauthValidator = new OAuthRequestValidator(accessToken, accessTokenSecret, consumerKey, consumerSecret);
                var context = new ServiceContext(realmId, intuitServicesType, oauthValidator);

                context.IppConfiguration.BaseUrl.Qbo = _qboBaseURL;
                
                var dataService = new DataService(context);

                var company = new Company();
                var cmps = dataService.FindAll(company);

```

When deploying the code to Windows 2012 R2 standard with Framework 4.7.1 installed, the last line `var cmps = dataService.FindAll(company);`

Throws the following error:
`System.MissingMethodException: Method not found: 'System.Net.HttpWebRequest Intuit.Ipp.Core.Rest.IRestHandler.PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters, System.Object, System.String)'.
   at Intuit.Ipp.DataService.DataService.FindAll[T](T entity, Int32 startPosition, Int32 maxResults)
`

The web app is published to a file directory and has been deployed and tested in both debug and release mode.

The web app targets 4.7.1 (in [Project] > Properties > Application).

Verified that Intuit.Ipp.Core.dll is in the /bin directory and is version 5.5.0.0

**Comment by nimisha84** [comment]
Hi Jeff,

I suspect this might be a dll hell issue on the server or the TLS1.2 registry key missing on the server. 
To verify if it not dll hell issue-
Can you try removing all references from your code and reference to IPP SDK from package.config. Then do a clean solution, add the IPP SDK and then do a clean build.
That should resolve your issue. Or you can even just try creating a clean sample app and adding the Nuget package and a test call using the SDK. See if you still get errors.
I am also sending the strong named assemblies to you
If you do not want to use the Nuget and just want to try using these strong named assmeblies, see if that resolves your issue.
Let me know how it goes.

To verify TLS1.2 settings-
See this registry key requirement for windows servers-

https://cloudblogs.microsoft.com/microsoftsecure/2017/07/20/tls-1-2-support-added-to-windows-server-2008/


Thanks,
Nimisha

**Comment by jeffhee** [comment]
Thank you, for the quick response! 👍 

Removing all references and reinstalling the SDK through nuget worked.
