### ISSUE TITLE
Not able to authorize Endpoint using v5.7 and v5.8 of QuickBooks-V3-DotNET-SDK

### ISSUE THREAD

**Issue by ServicePal** [intuit/QuickBooks-V3-DotNET-SDK#57]
App integration is running fine using v5.6, but after updating to either v5.7 or v5.8 using Nuget, AuthorizeEndpoint is failing.

Line 38 in the attached.
<img width="1400" alt="screen shot 2018-11-15 at 4 08 19 pm" src="https://user-images.githubusercontent.com/8471863/48589858-2b3dcc00-e8f2-11e8-8a95-e972debd2cc1.png">

"Value cannot be null. Parameter name: endpoint"
"System.ArgumentNullException:    at Intuit.Ipp.OAuth2PlatformClient.TokenClient..ctor(String endpoint, HttpMessageHandler innerHttpMessageHandler)
   at Intuit.Ipp.OAuth2PlatformClient.TokenClient..ctor(String endpoint, String clientId, String clientSecret, HttpMessageHandler innerHttpMessageHandler, AuthenticationStyle style)
   at Intuit.Ipp.OAuth2PlatformClient.TokenClient..ctor(String endpoint, String clientId, String clientSecret, AuthenticationStyle style)
   at ServicePal.WebApp.Synchronization.IntuitOAuth2Helper.<RefreshTokensAsync>d__1.MoveNext() in IntuitOAuth2Helper.cs:line 38

Just for kicks I did try: 
ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
That makes no difference.

**Comment by nimisha84** [comment]
This seems to me like a dll he'll issue. Please clean your references, do a clean solution, add the latest package n then retry. That should fix this issue.

**Comment by ServicePal** [comment]
I have checked all dll's in the bin folder. They all are all 5.8 version from ipp.Core to ipp.WebhooksService. 

<img width="605" alt="screen shot 2018-11-16 at 9 35 36 am" src="https://user-images.githubusercontent.com/8471863/48645218-dc4b7180-e999-11e8-9c2e-b4f3704b84a0.png">

I have tried removing the package from Nuget. doing fresh install. 
<img width="738" alt="screen shot 2018-11-16 at 12 16 01 pm" src="https://user-images.githubusercontent.com/8471863/48645244-ea998d80-e999-11e8-81d5-80e9555ee5e0.png">

<img width="966" alt="screen shot 2018-11-16 at 12 16 24 pm" src="https://user-images.githubusercontent.com/8471863/48645248-f08f6e80-e999-11e8-98b7-cc9968f486da.png">

The result is the same when I deploy our build to Azure. With 5.8 we might be able to call the integration a few times, but eventually it will fail when refreshing the access token. If I redeploy our build using 5.6, it runs without interruption.

**Comment by nimisha84** [comment]
I pushed 5.9.0 package to Nuget. Try downloading it and see if that resolves your issues. Did you try removing the bin n debug folders too after uninstslling the package?Generally that helps.

**Comment by wolfet** [comment]
I had this same issue when upgrading from 5.6.0 to 5.9.0. It looks like a bug introduced by this commit in DiscoveryClient.cs:

73ba9d68bbfca0f5a730a3f990b1abdc834a6a70

Passing in the full URL to DiscoveryClient used to work, but it does not now:

    DiscoveryClient discoveryClient = 
     new DiscoveryClient("https://developer.api.intuit.com/.well-known/openid_sandbox_configuration/");
    _discoveredEndpoint = discoveryClient.Get();

The above call returns the following error:

Error connecting to https://developer.api.intuit.com/.well-known/openid_sandbox_configuration/.well-known/openid_configuration/: Not Found

Passing in the AppEnvironment enum to the DiscoveryClient constructor resolves to the correct url:

    DiscoveryClient discoveryClient = new 
    DiscoveryClient(Intuit.Ipp.OAuth2PlatformClient.Helpers.AppEnvironment.Sandbox);

**Comment by ServicePal** [comment]
Huge thanks to Travis for digging in. Using the enum fixed the problem for us as well. We can now test with 5.9.0

**Comment by bobmanz** [comment]
Seeing this same behavior in 7.5.0.  Uninstalled and re-installed everything.  Oddly, the same code in a console app (instead of my Web API app) works...

Value cannot be null.
Parameter name: endpoint

   at Intuit.Ipp.OAuth2PlatformClient.TokenClient..ctor(String endpoint, HttpMessageHandler innerHttpMessageHandler)
   at Intuit.Ipp.OAuth2PlatformClient.TokenClient..ctor(String endpoint, String clientId, String clientSecret, HttpMessageHandler innerHttpMessageHandler, AuthenticationStyle style)
   at Intuit.Ipp.OAuth2PlatformClient.OAuth2Client.<RefreshTokenAsync>d__29.MoveNext()

**Comment by nimisha84** [comment]
7.5.0 is the SDK version that works with .Net full framework 4.6.1 or higher full frameworks.
Please make sure that you are using .Net frameworks 4.6.1 or higher.
Also, make sure that TLS1.2 is being used by your code. Enable fiddler logs.
Blog for TLS1.2 update- https://developer.intuit.com/hub/blog/2018/07/11/tls-1-0-1-1-deprecation-intuit-developers

Please follow the steps mentioned here- https://developer.intuit.com/hub/blog/2017/08/03/upgrading-your-apps-to-support-tls-1-2
to make just an http call to this url- https://tlstest.intuit.com
Code example-


ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12; //Add this just to be sure to use TLS1.2
var result = string.Empty;
using (var webClient = new WebClient())
{
result = webClient.DownloadString("https://tlstest.intuit.com");
}


Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers to confirm that your calls are using TLS1.2 protocol. If the calls works for the url above then your QBO api sandbox/prod calls will also work once the change goes live after Dec 31st, 2017. I have also added how the fiddler logs would look like once you test your code.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Do not Enable Decrypt Https traffic (https://textslashplain.com/2015/10/12/viewing-https-handshakes-in-fiddler/). That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.


So, for checking TLS version, you need to set Do not Enable Decrypt Https traffic in fiddler.
But I would also like to see the exact request and response which is failing, so send me the logs by running youe code again with fiddler having this setting-
Enable Decrypt Https traffic in fiddler.

Another thing to check is the registry keys if something works on your machine but not on client's machine-
https://stackoverflow.com/questions/43872575/net-framework-4-6-1-not-defaulting-to-tls-1-2
http://www.excel-fsm.com/ExcelFSM.html#IssuesAnswers
@rkasaraneni20

**Comment by bobmanz** [comment]
Thanks for the quick response!  The following code gives me the error:
The remote server returned an error: (503) Server Unavailable.

`ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
            var result = string.Empty;
            using (var webClient = new WebClient())
            {
                result = webClient.DownloadString("https://tlstest.intuit.com");
            }`

I'm running ASP.NET Web API using .NET Full Framework 4.6.1 on IIS Express.

**Comment by bobmanz** [comment]
GET https://tlstest.intuit.com/ HTTP/1.1
Host: tlstest.intuit.com


HTTP/1.1 503 Service Temporarily Unavailable
Server: awselb/2.0
Date: Fri, 14 Jun 2019 01:17:42 GMT
Content-Type: text/plain; charset=utf-8
Content-Length: 20
Connection: keep-alive

Resource Unavailable

**Comment by rkasaraneni20** [comment]
Can you please check whether the  DiscoveryURL is valid or not..

**Comment by bobmanz** [comment]
Figured it out! Saw an error in the OAuth2Client that it could not load 'System.Diagnostics.DiagnosticSource'.  Installed latest System.Net.Http and it resolved the issue.  Thanks!

**Comment by rkasaraneni20** [comment]
Thats nice to hear.. Let us know if you face any issues.
