### ISSUE TITLE
Problem when not using TLS1.2 because of in place update of 4.7.2

### ISSUE THREAD

**Issue by jsgoupil** [intuit/QuickBooks-V3-DotNET-SDK#59]
`DiscoveryClient` does not handle the TLS1.2 properly.
My project framework is on 4.7.1, and I have 4.7.2 installed on my computer. It works great.
Another developer does not have 4.7.2 so the TLS seems to be incorrect.

``` 
new OAuth2Client(clientId, clientSecret, redirectUrl, "sandbox").GetAuthorizationURL(scopes);
```

**Actual**
```
?client_id=ABC&response_type=code&scope=com.intuit.quickbooks.accounting&redirect_uri=http%3A%2F%2Flocalhost%3A27353%2Fcallback&state=DEF
```

**Expected**
```
https://appcenter.intuit.com/connect/oauth2?client_id=ABC&response_type=code&scope=com.intuit.quickbooks.accounting&redirect_uri=http%3A%2F%2Flocalhost%3A27353%2Fcallback&state=DEF
```
OR
throw an exception immediately instead of failing silently. Calling `GetBearerTokenAsync` will throw a null exception if the TLS is incorrect.

**Workaround**
Set the SecurityProtocol
```
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;
```

**Comment by jsgoupil** [comment]
Yes I have seen that, but I would recommend that you throw a better exception in case of a failure instead of silently allowing the calls to `GetAuthorizationURL` which actually does not work if Tls12 is not set.

**Comment by nimisha84** [comment]
Point taken. Will add this as an enhancement request to the .Net SDK- OAuth2PlatformClient lib.

**Comment by nimisha84** [comment]
We checked that current implementation handles all exceptions and throws a valid Discovery Response. The right way would be to check if DiscoveryResponse is not of exceptiontype and then read values.
