### ISSUE TITLE
Cannot instantiate ServiceContext

### ISSUE THREAD

**Issue by Bishbulb** [intuit/QuickBooks-V3-DotNET-SDK#6]
I get a null reference exception from the `ServiceContext` constructor, from within the `GetBaseURL` method. 

It looks like this code isn't handling the scenario where the BaseUrl.Qbo value starts out as null (instead of the empty string):
https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.Core/ServiceContext.cs#L390

**Comment by Bishbulb** [comment]
In my situation, I had to downgrade back to v2.9.1 (which is now unlisted on NuGet) because this was a blocking issue in 3.0.1.

**Comment by nimisha84** [comment]
Hi @Bishbulb - The code does handles it-
private string GetBaseURL()
        {
            this.IppConfiguration.Logger.CustomLogger.Log(TraceLevel.Info, "Called GetBaseURL method.");
            string baseurl = string.Empty;

           
            if (this.serviceType == IntuitServicesType.QBO)
            {
                baseurl = this.IppConfiguration.BaseUrl.Qbo;
                if (baseurl != "")
                {
                    if (!baseurl.EndsWith("/")) //Nimisha add check for /
                    {
                        baseurl = baseurl + "/";
                    }
                }

                if (string.IsNullOrEmpty(baseurl))
                {
                    baseurl = CoreConstants.QBO_BASEURL;
                }

                this.IppConfiguration.Logger.CustomLogger.Log(TraceLevel.Info, string.Format(CultureInfo.InvariantCulture, "BaseUrl set for QBO Service Type: {0}.", baseurl));
            }
            else if (this.serviceType == IntuitServicesType.IPS)
            {
                baseurl = this.IppConfiguration.BaseUrl.Ips;
                if (string.IsNullOrEmpty(baseurl))
                {
                    baseurl = CoreConstants.IPS_BASEURL;
                }

                this.IppConfiguration.Logger.CustomLogger.Log(TraceLevel.Info, string.Format(CultureInfo.InvariantCulture, "BaseUrl set for Intuit Platform Service Type: {0}.", baseurl));
            }

            return baseurl;
        }

Can you elaborate more on what you did? Or can you enable Fiddler logs to see what is happening in request and response- 
Download fiddler from google. Run it alongside your code to log raw request and response along with url and headers. 
When you download fiddler>open it-> just go to Tools->Fiddler Option->Enable(Tick Mark) Capture HTTPS connects->Enable Decrypt Https trafficThat is it.No other setting needs to be done.Dotnet localhost is by default captured in fiddler.So, after you enabled https traffic in fiddler.Just run your code.(Fiddler should be open)You will see request response getting logged in Fiddler. 
You should 'decode the raw request body' by clicking on the yellow bar in fiddle.Then go to File menu on top->Save all session-> Save the fiddler session. A .saz file is created.Zip that .saz file and attach to this ticket

**Comment by nimisha84** [comment]
This is the code for setting ServiceContext -OAuthRequestValidator oauthValidator = new OAuthRequestValidator(accessToken.Token, accessToken.TokenSecret, consumerKey, consumerSecret);
            ServiceContext serviceContext=  new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);

Base url can be set in web.config or serviceContext.IppConfiguration.BaseUrl.Qbo = "https://quickbooks.api.intuit.com/";

**Comment by Bishbulb** [comment]
@nimisha84 Look at line 392. On line 390, you checked if `baseurl != ""`, while on line 392 you then call `baseurl.EndsWith()`. This call will fail with a null reference exception if `baseurl` is null.

I repro'ed this by just instantiating the `ServiceContext` class without any attempt to configure the base URL via web.config. I cannot use the C# API to set the base url, because I am unable to construct the `ServiceContext` instance.

**Comment by Bishbulb** [comment]
@nimisha84 also - note that I didn't change anything in my code to reproduce this error - I just upgraded from 2.9.1 to 3.0.1 and encountered this.

**Comment by nimisha84** [comment]
Ok, Let me update the code the use the Null check before the addition of  /. Will update the Nuget package.

**Comment by Bishbulb** [comment]
@nimisha84 Great - thank you!

**Comment by nimisha84** [comment]
Please try now. 3.1.0 version

**Comment by Bishbulb** [comment]
@nimisha84 Version 3.1.0 fixed my issue, thanks again.

Do you have an idea of when the release notes for version 3.x of the SDK will be updated?

**Comment by nimisha84** [comment]
They should be released today. You can refer the same here- 
QuickBooks .NET SDK V3.1.0
Date: Jun 16, 2017

Overview
Minor version 9, 10 11 support added
Resolved bugs related to error logging
Updates to the .NET Class Library
Fixed Nuget package issue for NewtonSoft.Json dependency

Details
Updated dependency
Newtonsoft.Json (>= 10.0.2)
Minor version 9
Added support for minor version 9. Latest XSD: V3 minor version 9
Minor version 10
Added support for minor version 10. Latest XSD: V3 minor version 10
Minor version 11
Added support for minor version 11. Latest XSD: V3 minor version 11
Updates to the .NET Class Library


Updated the .NET Class Library to resolve the following bugs-
SDK-516 - .Net SDK Trace log will now expose error details when Retry Policy is used.
SDK-536 - .Net SDK will now return the array of errors in response instead of just the top level error.
SDK-521 - .Net SDK will handle the missing \ at the end of the QBO base url if it is not specified.
