### ISSUE TITLE
Configuration for ASP.NET Core on App Services

### ISSUE THREAD

**Issue by spelltwister** [intuit/QuickBooks-V3-DotNET-SDK#60]
This is similar to issue #50 but more specific to hosting in azure via app services.

ASP.NET Core 2.x apps do not use the web.config file and when hosting in azure, the build autogenerates the web.config file with no good support for manipulating it to add stuff so you just get the default one that hosts the app.

Currently, the ServiceContext internally news up a configuration reader that only looks for configuration section of web config.  **Please add support to change how / where configuration information is provided.**  Because of the current implementation, we have no way to override the baseUrl to point to development sandbox; it's always pointing to production service.

In the meantime, I'm going to fork this project and include the ability to read the baseUrl from appSettings.json / Environment Variables (used by Azure app services).

**Comment by nimisha84** [comment]
Thanks for the feedback. If you can do a pull for your requirement, it would be great. Also, to override web.config settings, we have override prorperties for everything available in serviceContext object.
Check all properties for ServiceContext overrides available here-

**Comment by spelltwister** [comment]
BaseUrl is a readonly property that cannot be overridden.  I will push some changes to my fork and you can decide if you want to pull them in.  Effectively, I'm going to add a way to inject the baseUrl.

**Comment by spelltwister** [comment]
oh, seems I did not follow the trail far enough.  Seems I can change the property on the IppConfiguration object after creating the service context.  this would achieve the same result as finding a way to get baseurl injected.  Also, when I hit build on the fresh clone it does not compile so I'm going to postpone changing the way configuration is read if I can just set it on the inner object.

**Comment by nimisha84** [comment]
Great. Let me know if you have any other questions?

**Comment by spelltwister** [comment]
Thanks so much for the super quick reply.  Is really amazing that you are able to stay on top of this so well!  🥇 👍

**Comment by nimisha84** [comment]
We are working on releasing the beta version of our DLLS for .net standard which you can use with .Net Core 2.1 projects.
Please let me know if you are interested in testing those out and giving us your feedback if you see any issues.

Thanks,
Nimisha

**Comment by nimisha84** [comment]
Please reply with your email ids, in case you are interested. I can send the zipped SDK dlls and steps to download any additional dependencies from Nuget. Later, in a few weeks when we release it, we will be releasing the NUget package with required dependencies.
