### ISSUE TITLE
SDK access to more Preferences, such as TimeTrackingFeatureEnabled and ProjectsEnabled? 

### ISSUE THREAD

**Issue by ServicePal** [intuit/QuickBooks-V3-DotNET-SDK#61]
Is that in the upcoming plans?

"OtherPrefs": {
      "NameValue": [
        {
          "Name": "SalesFormsPrefs.DefaultCustomerMessage",
          "Value": "Thank you for your business and have a great day!"
        },
        {
          "Name": "SalesFormsPrefs.DefaultItem",
          "Value": "19"
        },
        {
          "Name": "DTXCopyMemo",
          "Value": "true"
        },
        {
          "Name": "UncategorizedAssetAccountId",
          "Value": "125"
        },
        {
          "Name": "UncategorizedIncomeAccountId",
          "Value": "123"
        },
        {
          "Name": "UncategorizedExpenseAccountId",
          "Value": "124"
        },
        {
          "Name": "SFCEnabled",
          "Value": "true"
        },
        {
          "Name": "DataPartner",
          "Value": "false"
        },
        {
          "Name": "Vendor1099Enabled",
          "Value": "true"
        },
        {
          "Name": "TimeTrackingFeatureEnabled",
          "Value": "true"
        },
        {
          "Name": "FDPEnabled",
          "Value": "false"
        },
        {
          "Name": "ProjectsEnabled",
          "Value": "true"
        }
      ]
    },

**Comment by nimisha84** [comment]
Did you try using the latest minorversion=34 and still not get these fields?
These fields are supported even without any minorversio too.
Let me know if you see any issues.

**Comment by ServicePal** [comment]
Thanks. Got it working.
