### ISSUE TITLE
Support for Azure logging

### ISSUE THREAD

**Issue by ServicePal** [intuit/QuickBooks-V3-DotNET-SDK#62]
The Nuget description lists support for Azure logging, but as far as we know that's not the case.
https://www.nuget.org/packages/IppDotNetSdkForQuickBooksApiV3/

We asked about this a year ago, and imagine other cloud developers have the same requirement. We need to be able to catch error responses in a cloud environment.

**Comment by nimisha84** [comment]
Trace logs can still be enabled for the SDK and stored and viewed on Azure.
I wrote this sample app long back to show how trace logging is enabled for Azure.
I don't exactly remember the full details of settings on azure side but these steps should help.

Please see the dropbox link for the Azure sample project that I have for azure logging.-
https://www.dropbox.com/sh/6yblnww4ph5yt71/AAAxeiTSebEDjvYKg9juu9q2a?dl=0

Add your account details for storage account in the webrole.
Publish this to your cloud azure app by downloading the publish settings and using them in your publish profile.
Most imp-
Go to your cloud app->Configure tab->Enable all logging
http://blogs.msdn.com/b/mcsuksoldev/archive/2014/09/04/adding-trace-to-azure-web-sites-and-web-jobs.aspx
