### ISSUE TITLE
Error upgrading 6.0.0 to 7.2.1 - There was an error reflecting type 'Intuit.Ipp.Data.Invoice'.

### ISSUE THREAD

**Issue by bartdk-be** [intuit/QuickBooks-V3-DotNET-SDK#70]
- We did an upgrade to v7.2.1 and suddenly an exception is thrown. Is this a known issue ?

Using _Invoice invoice = new Invoice();_
Error : There was an error reflecting type 'Intuit.Ipp.Data.Invoice'.

   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(TypeModel model, String ns, ImportContext context, String dataType, XmlAttributes a, Boolean repeats, Boolean openModel, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportElement(TypeModel model, XmlRootAttribute root, String defaultNamespace, RecursionLimiter limiter)
   at System.Xml.Serialization.XmlReflectionImporter.ImportTypeMapping(Type type, XmlRootAttribute root, String defaultNamespace)
   at System.Xml.Serialization.XmlSerializer..ctor(Type type, String defaultNamespace)
   at Intuit.Ipp.Utility.XmlObjectSerializer.Serialize(Object entity)

**Comment by nimisha84** [comment]
Doesn't seem to related to the release. Please enable fiddler logs or just normal logs to get details of the error.

To manage exception handling in your code: 

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging 

If you still do not see error details, enable logging in code using these three lines: 

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator); 
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true; 
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs"; 

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging 

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers. 

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler. 

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by nimisha84** [comment]
.XmlSerializer..ctor -> .ctor generally refers to a dll hell issue too. Delete your bin and debug files. Remove all sdk references. Clean the sol. Readd the .net SDK and then build. See if that resolves the issue.
