### ISSUE TITLE
AllowOnlineACHPayment is not enabling ACH Payment Method for Generated Invoice

### ISSUE THREAD

**Issue by flyer299** [intuit/QuickBooks-V3-DotNET-SDK#71]
When I create an Invoice via the Quickbooks UI, I have an option to allow Free ACH Payment.  

When I create the same invoice via the Quickbooks SDK, I there are options for:
AllowOnlineACHPayment
and
allowCreditCard

Setting those to true does not result in the ACH option to be enabled.  

I have also tried setting:  AllowOnlineACHPaymentSpecified to true as well.  

Here is a code snippit:
`if(invoice.FleetPilot.FleetPilotGroup.allowACH || invoice.FleetPilot.FleetPilotGroup.allowCreditCard)
					{
						newInvoice.AllowIPNPayment = true;
						newInvoice.AllowIPNPaymentSpecified = true;
						newInvoice.AllowOnlinePayment = true;
						newInvoice.AllowOnlinePaymentSpecified = true;
					}

					newInvoice.AllowOnlineACHPayment = invoice.FleetPilot.FleetPilotGroup.allowACH;
					newInvoice.AllowOnlineACHPaymentSpecified = invoice.FleetPilot.FleetPilotGroup.allowACH;

					newInvoice.allowCreditCard = invoice.FleetPilot.FleetPilotGroup.allowCreditCard;
					newInvoice.AllowOnlineCreditCardPaymentSpecified = invoice.FleetPilot.FleetPilotGroup.allowCreditCard;

					var addedInvoice = dataService.Add<Invoice>(newInvoice);
					invoice.ExternalID = addedInvoice.Id;
					listInvoices.Add(addedInvoice);

					if (invoice.FleetPilot.FleetPilotGroup.sendInvoices)
					{
						dataService.SendEmail<Invoice>(addedInvoice, invoice.FleetPilot.Pilot.EmailAddress);
					}`

**Comment by nimisha84** [comment]
Check this - https://developer.intuit.com/app/developer/qbo/docs/api/accounting/most-commonly-used/invoice

AllowOnlineACHPayment
Optional
Boolean
Specifies if this invoice can be paid with online bank transfers and corresponds to the Free bank transfer online payment check box on the QuickBooks UI. **Active when Preferences.SalesFormsPrefs.ETransactionPaymentEnabled is set to true.**
If set to true, allow invoice to be paid with online bank transfers. The Free bank transfer online payment check box is checked on the QuickBooks UI for this invoice.
If set to false, online bank transfers are not allowed. The Free bank transfer online payment check box is not checked on the QuickBooks UI for this invoice.

Verify this setting first and also try using the latest minorversion=35 with your request.
