### ISSUE TITLE
Inconsistent Awaiter usage within the OAuth2Client

### ISSUE THREAD

**Issue by dteske25** [intuit/QuickBooks-V3-DotNET-SDK#72]
I ran into an issue while trying to use the `OAuth2Client.GetBearerTokenAsync` method. We are in an ASP.NET synchronous code base, and when we attempt to use `.GetAwaiter().GetResult()` to fetch the token response, the call never returns, and the thread hangs forever. 
I believe my specific issue can be fixed by adding `ConfigureAwait(false)` to the following line in https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/OAuth2Client.cs#L138 

This is based on the article I've listed below. I think it would be worthwhile to add `ConfigureAwait(false)` to all of the exposed async methods and make sure each awaited method in the call stack also uses `ConfigureAwait(false)`
http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

**Comment by nimisha84** [comment]
Hi @dteske25 - The writer of the blog himself mentions this-
Using ConfigureAwait(false) to avoid deadlocks is a dangerous practice. You would have to use ConfigureAwait(false) for every await in the transitive closure of all methods called by the blocking code, including all third- and second-party code. Using ConfigureAwait(false) to avoid deadlock is at best just a hack).

As the title of this post points out, the better solution is “Don’t block on async code”.

A better solution that he has suggested is to have async button clicks but since your have synchronous code, check these solutions too-

**Comment by dteske25** [comment]
I do agree with you and with the sentiment of the blog post, but this is something that is already being used elsewhere: 
- https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/TokenClient.cs#L134
- https://github.com/intuit/QuickBooks-V3-DotNET-SDK/blob/master/IPPDotNetDevKitCSV3/Code/Intuit.Ipp.OAuth2PlatformClient/Client/TokenRevocationClient.cs#L121

However, because the OAuth2Client awaits those calls without the `ConfigureAwait(false)`, we are unable to use any of those methods. Because it's already in the call stack for most of the OAuth2 related calls, I don't believe it would negatively impact the SDK, and it would enable us to use those solutions mentioned in the blog post or the Stackoverflow article you linked. As the SDK currently is, I simply cannot use the OAuth2Client class. None of the possible workarounds worked for me, and finally I had to resort to using the following:
```
 var tokenClient = new TokenClient(DiscoveryDoc.TokenEndpoint, ClientID, ClientSecret);
TokenResponse response = tokenClient.RequestTokenFromCodeAsync(AuthorizationCode, RedirectURI).GetAwaiter().GetResult();
``` 
which is exactly what the `OAuth2Client.GetBearerTokenAsync` does.

**Comment by nimisha84** [comment]
Makes sense. Thanks for the feedback. Please test the Latest 7.3.0 version of the SDK for this fix.
