### ISSUE TITLE
More detail needed in release notes

### ISSUE THREAD

**Issue by ServicePal** [intuit/QuickBooks-V3-DotNET-SDK#73]
https://developer.intuit.com/app/developer/qbo/docs/develop/release-notes/quickbooks-api-release-notes
For v1905 I noticed the following fix
"PLEX-1010 - Fix few V3 entities were not returning proper results when queried for balance and remaining amount"

How do we get more detail on that fix, and what the problem was? 

I read between the lines that if 3rd party apps queried customer.balance and stored that value, that perhaps we got an incorrect value.

**Comment by nimisha84** [comment]
Query on Credit Memos on `RemainingAmount` or `Balance` requires negative comparison for it to work. - This is the summary of that issue. It is just related to query operation, no data issue.
I have a request- for issues like these related to API,can you open a support ticket as it would be easier to track API issues there. We want to keep this channel only for SDK related issues.
