### ISSUE TITLE
PrefVendorRef not working

### ISSUE THREAD

**Issue by johnwc** [intuit/QuickBooks-V3-DotNET-SDK#75]
When querying and trying to update an Item, the field PrefVendorRef is not being set nor is it being updated when applied.

**Comment by johnwc** [comment]
Never mind, found that I had to change the minorVersion from 23 to 31. What happens if we do not set the minorVersion, will it always use the latest?

**Comment by nimisha84** [comment]
Yes, our latest SDK always uses latest minorversion as default. Current one is at 37.
