### ISSUE TITLE
Q: Connecting without human intervention

### ISSUE THREAD

**Issue by mike-niemand** [intuit/QuickBooks-V3-DotNET-SDK#77]
Hi All,

Is there something I'm missing re connecting without human intervention e.g. as a service to update payment, create an invoice etc?

**Comment by nimisha84** [comment]
No, you are right. We do not support that flow out of the box for Oauth2. You can try this workflow which solves your use case.
***For desktop apps/server apps/console apps and automated service type apps for Oauth2***

There is no way to bypass the Oauth process. You will have to do it at least once to make api calls.
So, if you have a desktop app/service then you can use Postman or Oauth2 playground we have, add the app keys and then get the Oauth2 tokens.
Hardcode them in your application. Then keep on refreshing access token using refreshtoken api call until refresh token expires in 100 days.
Then again get new access tokens by playground or postman and repeat api calls until refresh token expires. This would be a cycle of hardcoding tokens every 100 days.
Always save the latest refresh token in your code as once used refresh tokens can expire in 24hrs.

OAuth2 playground-https://developer.intuit.com/v2/ui#/playground

On the developer.intuit.com->Your app tab->Keys->Add this redirect url under your Prod app keys->Redirect url-https://developer.intuit.com/v2/OAuth2Playground/RedirectUrl

Postman-
https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0012_postman

On the developer.intuit.com->Your app tab->Keys->Add this redirect url under your Prod app keys ->Redirect url-https://www.getpostman.com/oauth2/callback

1)You get access token and refresh token manually using Postman or your web code where user authorizes
2)You hard code TOKENs in your code by saving the access token and latest refresh token in DB/permanaent store as access token expires every 1 hr and refresh token every 24hrs.
3)You can make calls without User interaction after refreshing access token using refresh token api once you get the access token from step 1 .
4)Every time refresh token api is called(check any of the web sample apps for oauth2 here-https://github.com/IntuitDeveloper), you have to save the latest value for access token and refresh token in DB.
5)Use the latest refresh token to get new access token and this process continues until 100 days.
6)Then again start with getting a new access token or whenever you have an expired token for various reasons. You will get a 401 error when access token expires or a 400 error when refresh token call fails to refresh access token. Read details in the docs - https://developer.intuit.com/app/developer/qbo/docs/develop/authentication-and-authorization.

**Comment by mike-niemand** [comment]
Thanks Nimisha,

I had read and thought it a bit strange but went this route in the
meantime. Please close.
