### ISSUE TITLE
Intermittent error BadGateway

### ISSUE THREAD

**Issue by andrada-malutan** [intuit/QuickBooks-V3-DotNET-SDK#78]
Details from the trace logs:
https://quickbooks.api.intuit.com/v3/company/xxx/query?minorversion=34&requestid=8b1c52c4e7e5474a99b9af0beb8a3ba3

Info -- 05-16-2019 08:01:26 --  - 0 - System.Net.HttpWebRequest PrepareRequest(Intuit.Ipp.Core.Rest.RequestParameters, System.Object, System.String, Boolean) - Adding the payload to request.
 Start dump: 
Select * FROM CompanyInfo

Error -- 05-16-2019 08:01:31 --  - 0 - System.String GetResponse(System.Net.HttpWebRequest) - Intuit.Ipp.Exception.IdsException: BadGateway

**Comment by MatthewSteeples** [comment]
Good luck with that. The API experiences relatively frequent drops in availability. You'll need to use the request id functionality (https://developer.intuit.com/app/developer/qbo/docs/develop/rest-api-features) and retry

**Comment by nimisha84** [comment]
If you do not have verbose logs, you will not get details. Enable file logs or run fiddler alongside code to get details of req and response.
To manage exception handling in your code:

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by nimisha84** [comment]
I see connection reset errors on server, intermittent issues.

**Comment by andrada-malutan** [comment]
Our web app is hosted in Azure, so there's no way to write on the disk. 
Per your indications, we were able to get the request/response logs plugged into our tracing service. 
The level is set to Verbose. 
What I posted in the original message was what I could get from the Trace when the error occurred. 

I'm not sure what more I can do considering these errors come and go and they cannot be reproduced on localhost as much as I've tried.

**Comment by nimisha84** [comment]
Now, that you stated Azure, from what we have seen earlier, the issue is with Azure not having TLS 1.2 enabled by default. Please enable that security protocol.

**Comment by MatthewSteeples** [comment]
While that's worth checking, that would only explain if they were unable to connect at all. It wouldn't explain an intermittent connectivity problem

**Comment by andrada-malutan** [comment]
That's right, the security protocol is set to TLS 1.2 and has been working since the Beta migration.
