### ISSUE TITLE
Unable to Link Purchase Order to Bill through SDK API

### ISSUE THREAD

**Issue by musmancinnova** [intuit/QuickBooks-V3-DotNET-SDK#79]
I am unable to Link Purchase Order to Bill Through SDK API.

**Comment by nimisha84** [comment]
It is not supported yet. After 1912 release when we start supporting it, we will release the new SDK version to support it. Currently you can only do a read.

**Comment by nimisha84** [comment]
https://developer.intuit.com/app/developer/qbo/docs/develop/release-notes/quickbooks-api-release-notes
