### ISSUE TITLE
QueryProcessingError when attempting to find all invoices

### ISSUE THREAD

**Issue by coberheide** [intuit/QuickBooks-V3-DotNET-SDK#81]
We are running into an issue when attempting to "FindAll" invoices for one of our customers using the DataService we get an IdsException:

>  BadRequestValidation Exception was thrown.Details:QueryProcessingError: To email address entered is invalid.

This seems to be a similar issue to the one [here](https://github.com/intuit/QuickBooks-V3-Java-SDK/issues/47) except the cdc issue was resolved and our customer was still able to reproduce the "FindAll" issue this afternoon.

Any help you could provide would be greatly appreciated.

**Comment by nimisha84** [comment]
Please enable fiddler and send us the logs for this issue using any of the 3 solutions below-
To manage exception handling in your code:

- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

**Comment by nimisha84** [comment]
Following up on your ticket. Closing this issue as your issue is related to api and not SDK

**Comment by xenno** [comment]
I've run into a similar issue in minor version 41. This is happening in production and I cannot replicate it on the sandbox. 
However, this is the responser:

Response Intuit_Tid header: ec2967cc-665f-426f-b9db-b5a573099f0c, Response Payload: {"Fault":{"Error":[{"Message":"Error processing query","Detail":"QueryProcessingError: To email address entered is invalid","code":"4002"}],"type":"ValidationFault"},"time":"2019-11-18T23:45:06.552-08:00"}
