### ISSUE TITLE
Unable to tax exempt a customer from SDK

### ISSUE THREAD

**Issue by musmancinnova** [intuit/QuickBooks-V3-DotNET-SDK#84]
I am unable to tax exempt a customer through QB SDK.

**Comment by nimisha84** [comment]
Hi,

Please enable logs and file a ticket on developer.intuit.com->Help with all the logs.
Our team will get back to you.
- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

- Set trace logging to verbose mode: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.

Thanks,
Nimisha

**Comment by nimisha84** [comment]
This issue you have reported here seems mostly an api issue and not related to SDK.
