### ISSUE TITLE
Taxable Customer updated through SDK not updating the UI.

### ISSUE THREAD

**Issue by musmancinnova** [intuit/QuickBooks-V3-DotNET-SDK#87]
I make a customer Taxable from SDK and get a success response . Here is the attached status.
![image](https://user-images.githubusercontent.com/45385707/62785224-a5922a00-bad9-11e9-9699-824f2527cd3d.png)
But on the UI of the company this customer is still tax exempted. When i try to edit this customer the UI shows that this customer is tax exempted. But from SDK I updated this customer to taxable.
So this checkbox should be removed while fetching the data from UI in Comapny. Kindly See this issue. As my client is asking me to make this change.
![image](https://user-images.githubusercontent.com/45385707/62785053-3a485800-bad9-11e9-9a31-c5515c94d96b.png)

**Comment by nimisha84** [comment]
Please enable logs and file a support ticket on developer.intuit.com->Help. I believe this more of an API issue. Please make sure that you use latest SDK version and latest minorversion=40 to retest again to make sure it is not something related to not using the correct minoversion.
- Enable request/response logs by overriding the configuration: https://developer.intuit.com/docs/0100_quickbooks_online/0400_tools/0005_sdks/0010.net_tools/0005_configuration#Logging

If you still do not see error details, enable logging in code using these three lines:

ServiceContext serviceContext = new ServiceContext(realmId, IntuitServicesType.QBO, oauthValidator);
serviceContext.IppConfiguration.Logger.RequestLog.EnableRequestResponseLogging = true;
serviceContext.IppConfiguration.Logger.RequestLog.ServiceRequestLoggingLocation = @"C:\IdsLogs";

or

- Download Fiddler from Google and run it alongside your code to log raw requests and responses along with URL and headers.

When you download Fiddler, open it, go to Tools > Fiddler Option > Enable (Tick Mark) Capture HTTPS connects > Enable Decrypt Https traffic. That’s it. No other setting is required. The .NET localhost is by default captured in Fiddler, so after you have enabled https traffic in Fiddler just run your code. (Fiddler should be open.) You will see requests and responses logged in Fiddler.

You should set 'decode the raw request body' by clicking on the yellow bar in Fiddler. Then go to the File menu on top, select Save all session > Save the fiddler session. A .saz file is created, which can be viewed later.
