### ISSUE TITLE
Modifying or overriding transaction Journals of a SalesItemLineDetail on invoice creation

### ISSUE THREAD

**Issue by PaulIvanov** [intuit/QuickBooks-V3-DotNET-SDK#89]
I have been trying to figure out how to modify or override the CoGs and inventory asset transactions when creating an invoice with an inventory product salesItemDetail. 

Is there a way to override those entries via the Invoice API? 

```
        lines.Add(new Line
		{
			DetailType = LineDetailTypeEnum.SalesItemLineDetail,
			DetailTypeSpecified = true,
			Amount = orderItem.TotalPrice,
			AmountSpecified = true,
			Description = $"{orderItem.ProductCode} - {orderItem.ProductName} ({decimal.Round(orderItem.WeightShipped,2)} lbs)",
				AnyIntuitObject = new SalesItemLineDetail
			{
				Qty = decimal.Round(orderItem.WeightShipped, 2),
				QtySpecified = true,
				AnyIntuitObject = orderItem.UnitPrice,
				ItemElementName = ItemChoiceType.UnitPrice,
				ItemRef = itemRef
			},
			
		});
```

![image](https://user-images.githubusercontent.com/13825788/62903530-d52e7580-bd17-11e9-8b1b-20f12be5aee9.png)

Being able to manually override these transactions via the invoice api is what I am after

**Comment by nimisha84** [comment]
We do not officially support his via the Invoice API or SDK but we do have a field which is called ItemAccountRef which was exposed only for linked txns of type Billable Expense when linked to invoice. You can do your testing and see if that works for your use case but again officially we do not support this. So, if it works now and fails later, then we really cannot gurantee you anything

**Comment by PaulIvanov** [comment]
Thank you @nimisha84  for replying so quickly!

**Comment by nimisha84** [comment]
no problem :)
