### ISSUE TITLE
Add support for Azure logging in the SDK

### ISSUE THREAD

**Issue by nimisha84** [intuit/QuickBooks-V3-DotNET-SDK#95]

**Comment by Mygeen** [comment]
When you say "Azure logging", what exactly do you mean by that? Do you want to add support for AppInsights?

**Comment by nimisha84** [comment]
I would say Azure Document DB or any storage blob/table based logging in Azure for the SDK events/api calls. I am currently working with Serilog. If you can wait until Friday, you can extend that.

**Comment by nimisha84** [comment]
Assigning to Keerti Purswani
