### ISSUE TITLE
Update Exceptions to concatenate and return all error details in one go 

### ISSUE THREAD

**Issue by nimisha84** [intuit/QuickBooks-V3-DotNET-SDK#96]
Using the SDK I'm adding an Intuit.Ipp.Data.JournalEntry object that does not pass the validation (which is ok). The reason for the failed validation is simple: there are 2 accounts objects referenced in the JournalEntry that have been deactivated by the user. However, when recovering the Intuit.Ipp.Exception.ValidationException I'm only receiving an error for the first account.
I need to get the complete list of failed validations and not just one at a time.
Here is the request and response from the API:
{
"DocNumber":"Pay 20190901",
"Line":[
{
"LineNum":"1",
"Description":"Test Line 1",
"Amount":100,
"DetailType":"JournalEntryLineDetail",
"JournalEntryLineDetail":{
"PostingType":"Debit",
"AccountRef":{
"name":"Impôt fédéral à payer",
"value":"101"
},
"ClassRef":{
"name":"Div_1-;desc01001_0-10;N/A;N/A",
"value":"5100000000000017240"
}
}
},
{
"LineNum":"2",
"Description":"Test Line 2",
"Amount":100,
"DetailType":"JournalEntryLineDetail",
"JournalEntryLineDetail":{
"PostingType":"Credit",
"AccountRef":{
"name":"Impôt provincial à payer",
"value":"102"
},
"ClassRef":{
"name":"Div_1-;desc01001_0-10;N/A;N/A",
"value":"5100000000000017240"
}
}
}
]
}

{
"responseHeader": {
"status": 400,
"message": "",
"intuitTid": "9051c2ca-aca8-47f1-8c7d-90e797f334d1",
"realmID": "4620816365016137870"
},
"response": {
"Fault": {
"Error": [
{
"Message": "Invalid Reference Id",
"Detail": "Invalid Reference Id : Account assigned to this transaction has been deleted. Before you can modify this transaction, you must restore 2140 Impôt fédéral à payer (deleted).",
"code": "2500",
"element": ""
}
],
"type": "ValidationFault"
},
"time": "2019-10-01T08:42:25.931-07:00"
}
}

**Comment by MavinsCode** [comment]
@nimisha84 I can take a look at this

**Comment by nimisha84** [comment]
Sorry, Amit vinayak is working on this one. Thanks for your interest. Please see if you can help with the ones not already taken.

**Comment by AmitEMV** [comment]
Hey sorry, that's my comment. Changed my username now. :)
