### ISSUE TITLE
ClassRef on items

### ISSUE THREAD

**Issue by Jesse-Hufstetler** [intuit/QuickBooks-V3-DotNET-SDK#98]
It seems that there's no ClassRef field on the Item object contained in the 8.1.0.0 NuGet package. I see the field in the code but somehow it didn't make it to the compiled binary in the NuGet package. Maybe it's an issue with your build scripts? One way or another, there is no ClassRef field on items using the latest QBO DotNet SDK. It's not in IntelliSense, it's not there when you decompile the binaries, etc.

**Comment by fjolin-intuit** [comment]
related to case: 00087266

**Comment by nimisha84** [comment]
This will be supported in the next release of SDK where schema supports mv=41 and classref field too.
Check the docs here- https://developer.intuit.com/app/developer/qbo/docs/api/accounting/all-entities/item - classref was added with mv =41. Current SDK schema supports mv=40.

**Comment by nimisha84** [comment]
Please check the latest release.
